Using MAPPING_STR=11100022, VERSION_DIR=v4_engoff
Running /platform/source/s01/v4_engoff/m11100022/m11100022_q10_t0.sh
/platform/source/s01/v4_engoff/m11100022/m11100022_q10_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_engoff/m11100022/m11100022_q10_t0.sh: line 7: sudo: command not found
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct-redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engoff/m11100022/m11100022_q11_t0.sh
Running /platform/source/s01/v4_engoff/m11100022/m11100022_q12_t0.sh
Running /platform/source/s01/v4_engoff/m11100022/m11100022_q13_t0.sh
0% [Working]            Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
0% [Working]0% [Waiting for headers]                        Get:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease [114 kB]
0% [2 InRelease 5631 B/114 kB 5%]                                 0% [Working]0% [Waiting for headers]                        Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
                        0% [Working]100% [Working]              Fetched 114 kB in 1s (128 kB/s)
Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Building dependency tree... 0%Building dependency tree... 0%Building dependency tree... 50%Building dependency tree... 50%Building dependency tree       
Reading state information... 0%Reading state information... 0%Reading state information... Done
python3 is already the newest version (3.8.2-0ubuntu2).
python3 set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Building dependency tree... 0%Building dependency tree... 0%Building dependency tree... 50%Building dependency tree... 50%Building dependency tree       
Reading state information... 0%Reading state information... 0%Reading state information... Done
python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Collecting git+https://github.com/pandas-dev/pandas.git
  Cloning https://github.com/pandas-dev/pandas.git to /tmp/pip-req-build-vf3j47__
  Running command git clone -q https://github.com/pandas-dev/pandas.git /tmp/pip-req-build-vf3j47__
[31m  ERROR: Error [Errno 2] No such file or directory: 'git' while executing command git clone -q https://github.com/pandas-dev/pandas.git /tmp/pip-req-build-vf3j47__[0m
[31mERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?[0m
Running /platform/source/s01/v4_engoff/m11100022/m11100022_q14_t0.sh
Running /platform/source/s01/v4_engoff/m11100022/m11100022_q15_t0.sh
/platform/source/s01/v4_engoff/m11100022/m11100022_q15_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_engoff/m11100022/m11100022_q15_t0.sh: line 7: sudo: command not found
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: redis in /usr/local/lib/python3.8/dist-packages (3.4.1)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engoff/m11100022/m11100022_q16_t0.sh
Running /platform/source/s01/v4_engoff/m11100022/m11100022_q17_t0.sh
0% [Working]            Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
0% [Working]0% [Waiting for headers]                        Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
                        0% [Working]20% [Working]             Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Building dependency tree... 0%Building dependency tree... 0%Building dependency tree... 50%Building dependency tree... 50%Building dependency tree       
Reading state information... 0%Reading state information... 0%Reading state information... Done
python3 is already the newest version (3.8.2-0ubuntu2).
python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct-redis) (3.4.1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engoff/m11100022/m11100022_q18_t0.sh
/platform/source/s01/v4_engoff/m11100022/m11100022_q18_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_engoff/m11100022/m11100022_q18_t0.sh: line 7: sudo: command not found
/platform/source/s01/v4_engoff/m11100022/m11100022_q18_t0.sh: line 10: sudo: command not found
Running /platform/source/s01/v4_engoff/m11100022/m11100022_q19_t0.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engoff/m11100022/m11100022_q1_t0.sh
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Running /platform/source/s01/v4_engoff/m11100022/m11100022_q20_t0.sh
0% [Working]            Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
0% [Working]0% [Waiting for headers]                        Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
0% [Waiting for headers]0% [Waiting for headers]                        Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
                        0% [Working]20% [Working]             Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Building dependency tree... 0%Building dependency tree... 0%Building dependency tree... 50%Building dependency tree... 50%Building dependency tree       
Reading state information... 0%Reading state information... 0%Reading state information... Done
python3 is already the newest version (3.8.2-0ubuntu2).
python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Building dependency tree... 0%Building dependency tree... 0%Building dependency tree... 50%Building dependency tree... 50%Building dependency tree       
Reading state information... 0%Reading state information... 0%Reading state information... Done
The following additional packages will be installed:
  libmysqlclient-dev libmysqlclient21 libssl-dev
Suggested packages:
  libssl-doc
The following NEW packages will be installed:
  default-libmysqlclient-dev libmysqlclient-dev libmysqlclient21 libssl-dev
0 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
Need to get 4321 kB of archives.
After this operation, 25.1 MB of additional disk space will be used.
0% [Working]            Get:1 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 libmysqlclient21 arm64 8.0.35-0ubuntu0.20.04.1 [1256 kB]
0% [1 libmysqlclient21 9965 B/1256 kB 1%]9% [1 libmysqlclient21 466 kB/1256 kB 37%]                                          28% [Working]             Get:2 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 libssl-dev arm64 1.1.1f-1ubuntu2.20 [1460 kB]
29% [2 libssl-dev 34.6 kB/1460 kB 2%]                                     60% [Waiting for headers]                         Get:3 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 libmysqlclient-dev arm64 8.0.35-0ubuntu0.20.04.1 [1601 kB]
61% [3 libmysqlclient-dev 35.5 kB/1601 kB 2%]                                             95% [Waiting for headers]                         Get:4 http://ports.ubuntu.com/ubuntu-ports focal/main arm64 default-libmysqlclient-dev arm64 1.0.5ubuntu2 [3932 B]
95% [4 default-libmysqlclient-dev 3932 B/3932 B 100%]                                                     100% [Working]              Fetched 4321 kB in 1s (3828 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package libmysqlclient21:arm64.
(Reading database ... (Reading database ... 5%(Reading database ... 10%(Reading database ... 15%(Reading database ... 20%(Reading database ... 25%(Reading database ... 30%(Reading database ... 35%(Reading database ... 40%(Reading database ... 45%(Reading database ... 50%(Reading database ... 55%(Reading database ... 60%(Reading database ... 65%(Reading database ... 70%(Reading database ... 75%(Reading database ... 80%(Reading database ... 85%(Reading database ... 90%(Reading database ... 95%(Reading database ... 100%(Reading database ... 14446 files and directories currently installed.)
Preparing to unpack .../libmysqlclient21_8.0.35-0ubuntu0.20.04.1_arm64.deb ...
Unpacking libmysqlclient21:arm64 (8.0.35-0ubuntu0.20.04.1) ...
Selecting previously unselected package libssl-dev:arm64.
Preparing to unpack .../libssl-dev_1.1.1f-1ubuntu2.20_arm64.deb ...
Unpacking libssl-dev:arm64 (1.1.1f-1ubuntu2.20) ...
Selecting previously unselected package libmysqlclient-dev.
Preparing to unpack .../libmysqlclient-dev_8.0.35-0ubuntu0.20.04.1_arm64.deb ...
Unpacking libmysqlclient-dev (8.0.35-0ubuntu0.20.04.1) ...
Selecting previously unselected package default-libmysqlclient-dev:arm64.
Preparing to unpack .../default-libmysqlclient-dev_1.0.5ubuntu2_arm64.deb ...
Unpacking default-libmysqlclient-dev:arm64 (1.0.5ubuntu2) ...
Setting up libmysqlclient21:arm64 (8.0.35-0ubuntu0.20.04.1) ...
Setting up libssl-dev:arm64 (1.1.1f-1ubuntu2.20) ...
Setting up libmysqlclient-dev (8.0.35-0ubuntu0.20.04.1) ...
Setting up default-libmysqlclient-dev:arm64 (1.0.5ubuntu2) ...
Processing triggers for libc-bin (2.31-0ubuntu9.12) ...
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct-redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engoff/m11100022/m11100022_q21_t0.sh
0% [Working]            Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
0% [Working]0% [Waiting for headers]                        Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
0% [Waiting for headers]0% [Waiting for headers]                        Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
                        0% [Working]20% [Working]             Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Building dependency tree... 0%Building dependency tree... 0%Building dependency tree... 50%Building dependency tree... 50%Building dependency tree       
Reading state information... 0%Reading state information... 0%Reading state information... Done
python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: redis in /usr/local/lib/python3.8/dist-packages (3.4.1)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engoff/m11100022/m11100022_q22_t0.sh
/platform/source/s01/v4_engoff/m11100022/m11100022_q22_t0.sh: line 4: sudo: command not found
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Running /platform/source/s01/v4_engoff/m11100022/m11100022_q2_t0.sh
/platform/source/s01/v4_engoff/m11100022/m11100022_q2_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_engoff/m11100022/m11100022_q2_t0.sh: line 7: sudo: command not found
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Running /platform/source/s01/v4_engoff/m11100022/m11100022_q3_t0.sh
Running /platform/source/s01/v4_engoff/m11100022/m11100022_q4_t0.sh
/platform/source/s01/v4_engoff/m11100022/m11100022_q4_t0.sh: line 5: sudo: command not found
Running /platform/source/s01/v4_engoff/m11100022/m11100022_q5_t0.sh
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Running /platform/source/s01/v4_engoff/m11100022/m11100022_q6_t0.sh
/platform/source/s01/v4_engoff/m11100022/m11100022_q6_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_engoff/m11100022/m11100022_q6_t0.sh: line 5: sudo: command not found
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: redis in /usr/local/lib/python3.8/dist-packages (3.4.1)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engoff/m11100022/m11100022_q7_t0.sh
/platform/source/s01/v4_engoff/m11100022/m11100022_q7_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_engoff/m11100022/m11100022_q7_t0.sh: line 7: sudo: command not found
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engoff/m11100022/m11100022_q8_t0.sh
Running /platform/source/s01/v4_engoff/m11100022/m11100022_q9_t0.sh
0% [Working]            Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
0% [Working]0% [Waiting for headers]                        Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
0% [Waiting for headers]0% [Waiting for headers]                        Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
                        0% [Working]20% [Working]             Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Building dependency tree... 0%Building dependency tree... 0%Building dependency tree... 50%Building dependency tree... 50%Building dependency tree       
Reading state information... 0%Reading state information... 0%Reading state information... Done
python3 is already the newest version (3.8.2-0ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Building dependency tree... 0%Building dependency tree... 0%Building dependency tree... 50%Building dependency tree... 50%Building dependency tree       
Reading state information... 0%Reading state information... 0%Reading state information... Done
python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pymysql in /usr/local/lib/python3.8/dist-packages (1.1.0)
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct-redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m11100022/m11100022_q10_t0.py /platform/output/s01/v4_engoff/m11100022/m11100022_q10_t0.csv /platform/expected/s01/q10.csv
/platform/source/s01/v4_engoff/m11100022/m11100022_q10_t0.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  mysql_df = pd.read_sql(customer_query, mysql_conn)
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m11100022/m11100022_q10_t0.py", line 22, in <module>
    orders_df = pd.read_json(redis_client.get('orders'))
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m11100022/m11100022_q11_t0.py /platform/output/s01/v4_engoff/m11100022/m11100022_q11_t0.csv /platform/expected/s01/q11.csv
>>> Expected ((2541, 2))
      PS_PARTKEY        VALUE
0          12098  16227681.21
1           5134  15709338.52
2          13334  15023662.41
3          17052  14351644.20
4           3452  14070870.14
...          ...          ...
2536       19870   1007919.36
2537       18564   1007416.20
2538       10179   1004920.00
2539         883   1004650.68
2540        3627   1004461.04

[2541 rows x 2 columns]

>>> Actual ((0, 2))
Empty DataFrame
Columns: [PARTKEY, VALUE]
Index: []

Score.fail_wrong_output
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m11100022/m11100022_q12_t0.py /platform/output/s01/v4_engoff/m11100022/m11100022_q12_t0.csv /platform/expected/s01/q12.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m11100022/m11100022_q12_t0.py", line 12, in <module>
    orders_df = pd.read_json(redis_connection.get('orders'), orient='records')
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m11100022/m11100022_q13_t0.py /platform/output/s01/v4_engoff/m11100022/m11100022_q13_t0.csv /platform/expected/s01/q13.csv
/platform/source/s01/v4_engoff/m11100022/m11100022_q13_t0.py:13: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  customer_df = pd.read_sql(customer_query, mysql_connection)
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m11100022/m11100022_q13_t0.py", line 19, in <module>
    orders_df = pd.read_json(redis_connection.get('orders'))
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m11100022/m11100022_q14_t0.py /platform/output/s01/v4_engoff/m11100022/m11100022_q14_t0.csv /platform/expected/s01/q14.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m11100022/m11100022_q14_t0.py", line 23, in <module>
    lineitem_df = pd.read_json(redis_client.get('lineitem'))
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m11100022/m11100022_q15_t0.py /platform/output/s01/v4_engoff/m11100022/m11100022_q15_t0.csv /platform/expected/s01/q15.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m11100022/m11100022_q15_t0.py", line 23, in <module>
    lineitem_df = pd.read_json(redis_conn.get('lineitem'))
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m11100022/m11100022_q16_t0.py /platform/output/s01/v4_engoff/m11100022/m11100022_q16_t0.csv /platform/expected/s01/q16.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m11100022/m11100022_q16_t0.py", line 46, in <module>
    cursor.execute(supplier_query, part_keys)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'S_NAME' in 'order clause'")
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m11100022/m11100022_q17_t0.py /platform/output/s01/v4_engoff/m11100022/m11100022_q17_t0.csv /platform/expected/s01/q17.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m11100022/m11100022_q17_t0.py", line 17, in <module>
    lineitem_df = pd.read_json(redis_client.get('lineitem'))
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m11100022/m11100022_q18_t0.py /platform/output/s01/v4_engoff/m11100022/m11100022_q18_t0.csv /platform/expected/s01/q18.csv
/platform/source/s01/v4_engoff/m11100022/m11100022_q18_t0.py:19: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  customers_df = pd.read_sql(mysql_query, mysql_conn)
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m11100022/m11100022_q18_t0.py", line 27, in <module>
    orders_df = pd.read_json(orders_str)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m11100022/m11100022_q19_t0.py /platform/output/s01/v4_engoff/m11100022/m11100022_q19_t0.csv /platform/expected/s01/q19.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m11100022/m11100022_q19_t0.py", line 28, in <module>
    lineitem_df = pd.read_json(lineitem_data)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m11100022/m11100022_q1_t0.py /platform/output/s01/v4_engoff/m11100022/m11100022_q1_t0.csv /platform/expected/s01/q1.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m11100022/m11100022_q1_t0.py", line 38, in <module>
    main()
  File "/platform/source/s01/v4_engoff/m11100022/m11100022_q1_t0.py", line 16, in main
    df_lineitem = load_data_from_redis(redis_host, redis_port, redis_dbname, tablename)
  File "/platform/source/s01/v4_engoff/m11100022/m11100022_q1_t0.py", line 7, in load_data_from_redis
    df = pd.read_json(dr.get(tablename))
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m11100022/m11100022_q20_t0.py /platform/output/s01/v4_engoff/m11100022/m11100022_q20_t0.csv /platform/expected/s01/q20.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m11100022/m11100022_q20_t0.py", line 49, in <module>
    df_lineitem = get_redis_data()
  File "/platform/source/s01/v4_engoff/m11100022/m11100022_q20_t0.py", line 42, in get_redis_data
    df_lineitem = pd.DataFrame(eval(redis_client.get('lineitem')))
TypeError: eval() arg 1 must be a string, bytes or code object
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m11100022/m11100022_q21_t0.py /platform/output/s01/v4_engoff/m11100022/m11100022_q21_t0.csv /platform/expected/s01/q21.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m11100022/m11100022_q21_t0.py", line 38, in <module>
    orders_df = pd.read_json(redis_client.get('orders'), orient='records')
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m11100022/m11100022_q22_t0.py /platform/output/s01/v4_engoff/m11100022/m11100022_q22_t0.csv /platform/expected/s01/q22.csv
/platform/source/s01/v4_engoff/m11100022/m11100022_q22_t0.py:51: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['COUNTRY_CODE'] = final_df['C_PHONE'].str[:2]
>>> Expected ((4, 3))
   CNTRYCODE  NUMCUST  TOTACCTBAL
0         20       91   666158.10
1         21      101   760953.55
2         22      106   759804.81
3         30       87   646748.02

>>> Actual ((4, 3))
   COUNTRY_CODE  avg_acct_balance  num_customers
0            20       4820.828132            182
1            21       5146.711055            199
2            22       5227.689027            185
3            30       5190.657840            162

Head row similarity: 0.5472154963680388
Score.fail_wrong_output
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m11100022/m11100022_q2_t0.py /platform/output/s01/v4_engoff/m11100022/m11100022_q2_t0.csv /platform/expected/s01/q2.csv
>>> Expected ((44, 8))
            N_NAME          P_MFGR  P_PARTKEY  S_ACCTBAL                                 S_ADDRESS                                          S_COMMENT              S_NAME          S_PHONE
0   UNITED KINGDOM  Manufacturer#5      13120    9828.21                              x5U7MBZmwfG9             s the slyly even ideas poach fluffily   Supplier#000000647  33-258-202-4782
1           FRANCE  Manufacturer#1       3563    9508.37         INWNH2w,OOWgNDq0BRCcBwOMQc6PdFDc4  ests sleep quickly express ideas. ironic ideas...  Supplier#000000070  16-821-608-1166
2           FRANCE  Manufacturer#4      17268    9508.37         INWNH2w,OOWgNDq0BRCcBwOMQc6PdFDc4  ests sleep quickly express ideas. ironic ideas...  Supplier#000000070  16-821-608-1166
3          ROMANIA  Manufacturer#5      10021    9453.01                  ,6HYXb4uaHITmtMBj4Ak57Pd  gular frets. permanently special multipliers b...  Supplier#000000802  29-342-882-6463
4          ROMANIA  Manufacturer#4      13275    9453.01                  ,6HYXb4uaHITmtMBj4Ak57Pd  gular frets. permanently special multipliers b...  Supplier#000000802  29-342-882-6463
5   UNITED KINGDOM  Manufacturer#1      13325    9192.10            nJ 2t0f7Ve,wL1,6WzGBJLNBUCKlsV  es across the carefully express accounts boost...  Supplier#000000115  33-597-248-1220
6          GERMANY  Manufacturer#4       4958    9032.15                            8grA EHBnwOZhO                      nding dependencies nag furiou  Supplier#000000959  17-108-642-3106
7           RUSSIA  Manufacturer#3      11810    8702.02           MaVf XgwPdkiX4nfJGOis8Uu2zKiIZH  oss the deposits cajole carefully even pinto b...  Supplier#000000333  32-508-202-6136
8           FRANCE  Manufacturer#2      10551    8615.50         8qh4tezyScl5bidLAysvutB,,ZI2dn6xP  y quickly regular deposits? quickly pending pa...  Supplier#000000812  16-585-724-6633
9           FRANCE  Manufacturer#4      13811    8615.50         8qh4tezyScl5bidLAysvutB,,ZI2dn6xP  y quickly regular deposits? quickly pending pa...  Supplier#000000812  16-585-724-6633
10          RUSSIA  Manufacturer#4       6854    8488.53                           E Sv9brQVf43Mzz  ages. carefully final excuses nag finally. car...  Supplier#000000367  32-458-198-9557
11          FRANCE  Manufacturer#3      11384    8430.52       IUzsmT,2oBgjhWP2TlXTL6IkJH,4h,1SJRt  ites among the always final ideas kindle accor...  Supplier#000000646  16-601-220-5489
12          RUSSIA  Manufacturer#5       4637    8271.39               rBDNgCr04x0sfdzD5,gFOutCiG2  s cajole quickly special requests. quickly ent...  Supplier#000000146  32-792-619-3155
13          RUSSIA  Manufacturer#4        323    8096.98               2O8 sy9g2mlBOuEjzj0pA2pevk,  ully after the regular requests. slyly final d...  Supplier#000000574  32-866-246-8752
14  UNITED KINGDOM  Manufacturer#2       7655    7392.78                          RtsXQ,SunkA XHy9                   ake carefully across the quickly  Supplier#000000170  33-803-340-5398
15         GERMANY  Manufacturer#5      10956    7205.20                  VtaNKN5Mqui5yh7j2ldd5waf   excuses wake express deposits. furiously care...  Supplier#000000477  17-180-144-7991
16  UNITED KINGDOM  Manufacturer#5      13217    6820.35                     s,4TicNGB4uO6PaSqNBUq  s unwind silently furiously regular courts. fi...  Supplier#000000007  33-990-965-2201
17          FRANCE  Manufacturer#3       4191    6721.70                          P3O5p UFz1QsLmZX                   ect blithely blithely final acco  Supplier#000000954  16-537-341-8517
18         GERMANY  Manufacturer#2      10735    6329.90                      Wx4dQwOAwWjfSCGupfrM                 ironic forges cajole blithely agai  Supplier#000000996  17-447-811-3282
19          RUSSIA  Manufacturer#1      18139    6173.87                qcor1u,vJXAokjnL5,dilyYNmh  blithely pending packages cajole furiously sly...  Supplier#000000408  32-858-724-2950
20          RUSSIA  Manufacturer#4      13784    5364.99  W VkHBpQyD3qjQjWGpWicOpmILFehmEdWy67kUGY      packages boost carefully. express ideas along  Supplier#000000785  32-297-653-2203
21         GERMANY  Manufacturer#1      16327    5069.27                               SMm24d WG62           he unusual ideas. slyly final packages a  Supplier#000000328  17-231-513-5721
22         ROMANIA  Manufacturer#5       7320    4941.88                           pLngFl5yeMcHyov                         y final requests impress s  Supplier#000000321  29-573-279-1406
23          RUSSIA  Manufacturer#1      12238    4672.25   XO101kgHrJagK2FL1U6QCaTE ncCsMbeuTgK6o8  arls wake furiously deposits. even, regular depen  Supplier#000000239  32-396-654-6826
24          RUSSIA  Manufacturer#3       5679    4586.49     UhvDfdEfJh,Qbe7VZb8uSGO2TU 0jEa6nXZXE   the regularly regular dependencies. carefully...  Supplier#000000680  32-522-382-1620
25          FRANCE  Manufacturer#5      18344    4518.31                  pVyWsjOidpHKp4NfKU4yLeym  ts detect along the foxes. final Tiresias are....  Supplier#000000149  16-660-553-2456
26          FRANCE  Manufacturer#2      18972    4315.15                                SF7dR8V5pK  ronic orbits are furiously across the requests...  Supplier#000000509  16-298-154-3365
27          FRANCE  Manufacturer#4       8036    3526.53                               a,liVofXbCJ                          lar dinos nag slyly brave  Supplier#000000553  16-599-552-3755
28          FRANCE  Manufacturer#3      17018    3526.53                               a,liVofXbCJ                          lar dinos nag slyly brave  Supplier#000000553  16-599-552-3755
29         GERMANY  Manufacturer#4       4841    3294.68                            KIFxV73eovmwhh  e slyly special foxes. furiously unusual depos...  Supplier#000000350  17-113-181-4017
30          RUSSIA  Manufacturer#4       1015    2972.26      YjP5C55zHDXL7LalK27zfQnwejdpin4AMpvh     ously express ideas haggle quickly dugouts? fu  Supplier#000000016  32-822-502-4215
31         ROMANIA  Manufacturer#2       3080    2963.09                              iYzUIypKhC0Y  eep blithely regular dependencies. blithely re...  Supplier#000000840  29-781-337-5584
32         ROMANIA  Manufacturer#2      13981    2221.25                        lwZ I15rq9kmZXUNhl  nal foxes eat slyly about the fluffily permane...  Supplier#000000771  29-986-304-9006
33          FRANCE  Manufacturer#3      18103    1381.97     Dcl4yGrzqv3OPeRO49bKh78XmQEDR7PBXIs0m  gular ideas. bravely bold deposits haggle thro...  Supplier#000000104  16-434-972-6922
34         ROMANIA  Manufacturer#4       8363     906.07   utbplAm g7RmxVfYoNdhcrQGWuzRqPe0qHSwbKw  ickly unusual requests cajole. accounts above ...  Supplier#000000138  29-533-434-6776
35          RUSSIA  Manufacturer#2      11276     765.69                             jwFN7ZB3T9sMF  nusual requests. furiously unusual epitaphs in...  Supplier#000000799  32-579-339-1495
36         ROMANIA  Manufacturer#3       6213     727.89        XckbzsAgBLbUkdfjgJEPjmUMTM8ebSMEvI  gular excuses. furiously regular excuses sleep...  Supplier#000000470  29-165-289-1523
37          RUSSIA  Manufacturer#4       4888     683.07                              oWekiBV6s,1g                    ly regular requests cajole abou  Supplier#000000651  32-181-426-4490
38          FRANCE  Manufacturer#1       2037     167.56                          6Bk06GVtwZaKqg01    the theodolites. ironic, ironic deposits above   Supplier#000000290  16-675-286-5102
39  UNITED KINGDOM  Manufacturer#2       9430      91.39     a,UE,6nRVl2fCphkOoetR1ajIzAEJ1Aa1G1HV       pinto beans. carefully express requests hagg  Supplier#000000949  33-332-697-2768
40         ROMANIA  Manufacturer#4      17242    -314.06             VmXQl ,vY8JiEseo8Mv4zscvNCfsY                    bold deposits. carefully even d  Supplier#000000510  29-207-852-3454
41         GERMANY  Manufacturer#5       2156    -820.89        LyXUYFz7aXrvy65kKAbTatGzGS,NDBcdtD   y final, slow theodolites. furiously regular req  Supplier#000000409  17-719-517-9836
42         ROMANIA  Manufacturer#5       9926    -845.44             hQvlBqbqqnA5Dgo1BffRBX78tkkRu                         ctions. carefully sly requ  Supplier#000000704  29-300-896-5991
43         GERMANY  Manufacturer#1       5797    -942.73                           Rc7U1cRUhYs03JD  slyly furiously final decoys; silent, special ...  Supplier#000000563  17-108-537-2691

>>> Actual ((0, 8))
Empty DataFrame
Columns: [N_NAME, P_MFGR, P_PARTKEY, S_ACCTBAL, S_ADDRESS, S_COMMENT, S_NAME, S_PHONE]
Index: []

Score.fail_wrong_output
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m11100022/m11100022_q3_t0.py /platform/output/s01/v4_engoff/m11100022/m11100022_q3_t0.csv /platform/expected/s01/q3.csv
/platform/source/s01/v4_engoff/m11100022/m11100022_q3_t0.py:24: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  mysql_df = pd.read_sql(mysql_query, mysql_conn)
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m11100022/m11100022_q3_t0.py", line 31, in <module>
    orders_df = pd.read_json(redis_conn.get('orders'))
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m11100022/m11100022_q4_t0.py /platform/output/s01/v4_engoff/m11100022/m11100022_q4_t0.csv /platform/expected/s01/q4.csv
>>> Expected ((5, 2))
   ORDER_COUNT  O_ORDERPRIORITY
0          999         1-URGENT
1          997           2-HIGH
2         1031         3-MEDIUM
3          989  4-NOT SPECIFIED
4         1077            5-LOW

>>> Actual ((5, 2))
   O_ORDERPRIORITY  order_count
0         1-URGENT         1013
1           2-HIGH         1012
2         3-MEDIUM         1041
3  4-NOT SPECIFIED         1006
4            5-LOW         1093

Head row similarity: 0.7643979057591623
Score.success_approx
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m11100022/m11100022_q5_t0.py /platform/output/s01/v4_engoff/m11100022/m11100022_q5_t0.csv /platform/expected/s01/q5.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m11100022/m11100022_q5_t0.py", line 30, in <module>
    nations = list(mongo_db.nation.find({'N_REGIONKEY': {"$in": mongo_db.region.find({'R_NAME': 'ASIA'}, {'R_REGIONKEY': 1})}}, {'_id': 0}))
  File "/usr/local/lib/python3.8/dist-packages/pymongo/cursor.py", line 1264, in next
    if len(self.__data) or self._refresh():
  File "/usr/local/lib/python3.8/dist-packages/pymongo/cursor.py", line 1181, in _refresh
    self.__send_message(q)
  File "/usr/local/lib/python3.8/dist-packages/pymongo/cursor.py", line 1060, in __send_message
    response = client._run_operation(
  File "/usr/local/lib/python3.8/dist-packages/pymongo/_csot.py", line 107, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymongo/mongo_client.py", line 1394, in _run_operation
    return self._retryable_read(
  File "/usr/local/lib/python3.8/dist-packages/pymongo/mongo_client.py", line 1492, in _retryable_read
    return self._retry_internal(
  File "/usr/local/lib/python3.8/dist-packages/pymongo/_csot.py", line 107, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymongo/mongo_client.py", line 1453, in _retry_internal
    return _ClientConnectionRetryable(
  File "/usr/local/lib/python3.8/dist-packages/pymongo/mongo_client.py", line 2315, in run
    return self._read() if self._is_read else self._write()
  File "/usr/local/lib/python3.8/dist-packages/pymongo/mongo_client.py", line 2444, in _read
    return self._func(self._session, self._server, conn, read_pref)  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/pymongo/mongo_client.py", line 1390, in _cmd
    return server.run_operation(
  File "/usr/local/lib/python3.8/dist-packages/pymongo/helpers.py", line 322, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pymongo/server.py", line 130, in run_operation
    message = operation.get_message(read_preference, conn, use_cmd)
  File "/usr/local/lib/python3.8/dist-packages/pymongo/message.py", line 426, in get_message
    request_id, msg, size, _ = _op_msg(
  File "/usr/local/lib/python3.8/dist-packages/pymongo/message.py", line 762, in _op_msg
    return _op_msg_uncompressed(flags, command, identifier, docs, opts)
bson.errors.InvalidDocument: cannot encode object: <pymongo.cursor.Cursor object at 0xffff86334520>, of type: <class 'pymongo.cursor.Cursor'>
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m11100022/m11100022_q6_t0.py /platform/output/s01/v4_engoff/m11100022/m11100022_q6_t0.csv /platform/expected/s01/q6.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m11100022/m11100022_q6_t0.py", line 25, in <module>
    lineitem_df = pd.read_json(lineitem_data)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m11100022/m11100022_q7_t0.py /platform/output/s01/v4_engoff/m11100022/m11100022_q7_t0.csv /platform/expected/s01/q7.csv
/platform/source/s01/v4_engoff/m11100022/m11100022_q7_t0.py:28: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  india_nkey = india_japan_nations[nation_df['N_NAME'] == 'INDIA']['N_NATIONKEY'].iloc[0]
/platform/source/s01/v4_engoff/m11100022/m11100022_q7_t0.py:29: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  japan_nkey = india_japan_nations[nation_df['N_NAME'] == 'JAPAN']['N_NATIONKEY'].iloc[0]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/internals/construction.py", line 934, in _finalize_columns_and_data
    columns = _validate_or_indexify_columns(contents, columns)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/internals/construction.py", line 981, in _validate_or_indexify_columns
    raise AssertionError(
AssertionError: 8 columns passed, passed data had 7 columns

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m11100022/m11100022_q7_t0.py", line 37, in <module>
    supplier_df = pd.DataFrame(supplier_data, columns=[desc[0] for desc in mysql_cursor.description])
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py", line 782, in __init__
    arrays, columns, index = nested_data_to_arrays(
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/internals/construction.py", line 498, in nested_data_to_arrays
    arrays, columns = to_arrays(data, columns, dtype=dtype)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/internals/construction.py", line 840, in to_arrays
    content, columns = _finalize_columns_and_data(arr, columns, dtype)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/internals/construction.py", line 937, in _finalize_columns_and_data
    raise ValueError(err) from err
ValueError: 8 columns passed, passed data had 7 columns
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m11100022/m11100022_q8_t0.py /platform/output/s01/v4_engoff/m11100022/m11100022_q8_t0.csv /platform/expected/s01/q8.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m11100022/m11100022_q8_t0.py", line 40, in <module>
    supplier_df = mysql_query(supplier_query)
  File "/platform/source/s01/v4_engoff/m11100022/m11100022_q8_t0.py", line 11, in mysql_query
    cursor.execute(query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'tpch.nation' doesn't exist")
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m11100022/m11100022_q9_t0.py /platform/output/s01/v4_engoff/m11100022/m11100022_q9_t0.csv /platform/expected/s01/q9.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m11100022/m11100022_q9_t0.py", line 64, in <module>
    mysql_data = get_mysql_data(mysql_query, mysql_connection_params)
  File "/platform/source/s01/v4_engoff/m11100022/m11100022_q9_t0.py", line 17, in get_mysql_data
    cursor.execute(query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'p.P_TYPE' in 'field list'")
Score.fail_execute
