Using MAPPING_STR=22221111, VERSION_DIR=v4_engoff
Running /platform/source/s01/v4_engoff/m22221111/m22221111_q10_t0.sh
0% [Working]            Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
0% [Working]0% [Waiting for headers]                        Get:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease [114 kB]
0% [2 InRelease 14.3 kB/114 kB 13%]                                   0% [Working]0% [Waiting for headers]                        Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
0% [Waiting for headers]0% [Waiting for headers]                        Get:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease [114 kB]
0% [4 InRelease 2687 B/114 kB 2%]                                 0% [Working]24% [Working]             Get:5 http://ports.ubuntu.com/ubuntu-ports focal-security/main arm64 Packages [2408 kB]
24% [5 Packages 5581 B/2408 kB 0%]                                  77% [Working]77% [5 Packages store 0 B] [Waiting for headers]77% [Connecting to ports.ubuntu.com (185.125.190.39)]                                                     Get:6 http://ports.ubuntu.com/ubuntu-ports focal-security/universe arm64 Packages [1023 kB]
                                                     77% [6 Packages 4134 B/1023 kB 0%]88% [6 Packages 489 kB/1023 kB 48%]                                   99% [Working]99% [6 Packages store 0 B]                          100% [Working]              Fetched 3659 kB in 2s (1545 kB/s)
Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Building dependency tree... 0%Building dependency tree... 0%Building dependency tree... 50%Building dependency tree... 50%Building dependency tree       
Reading state information... 0%Reading state information... 0%Reading state information... Done
python3 is already the newest version (3.8.2-0ubuntu2).
python3 set to manually installed.
python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Running /platform/source/s01/v4_engoff/m22221111/m22221111_q11_t0.sh
/platform/source/s01/v4_engoff/m22221111/m22221111_q11_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_engoff/m22221111/m22221111_q11_t0.sh: line 5: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engoff/m22221111/m22221111_q12_t0.sh
/platform/source/s01/v4_engoff/m22221111/m22221111_q12_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_engoff/m22221111/m22221111_q12_t0.sh: line 7: sudo: command not found
/platform/source/s01/v4_engoff/m22221111/m22221111_q12_t0.sh: line 8: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Running /platform/source/s01/v4_engoff/m22221111/m22221111_q13_t0.sh
/platform/source/s01/v4_engoff/m22221111/m22221111_q13_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_engoff/m22221111/m22221111_q13_t0.sh: line 7: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Running /platform/source/s01/v4_engoff/m22221111/m22221111_q14_t0.sh
/platform/source/s01/v4_engoff/m22221111/m22221111_q14_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_engoff/m22221111/m22221111_q14_t0.sh: line 7: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct-redis) (3.4.1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4_engoff/m22221111/m22221111_q15_t0.sh
0% [Working]            Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
0% [Working]0% [Waiting for headers]                        Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
0% [Waiting for headers]0% [Waiting for headers]                        Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
                        0% [Working]0% [Waiting for headers]                        Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
                        0% [Working]20% [Working]             Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Reading package lists... 0%Reading package lists... 0%Reading package lists... 0%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 6%Reading package lists... 60%Reading package lists... 60%Reading package lists... 61%Reading package lists... 61%Reading package lists... 74%Reading package lists... 74%Reading package lists... 75%Reading package lists... 75%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 81%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 82%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 94%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... 99%Reading package lists... Done
Building dependency tree... 0%Building dependency tree... 0%Building dependency tree... 50%Building dependency tree... 50%Building dependency tree       
Reading state information... 0%Reading state information... 0%Reading state information... Done
python3 is already the newest version (3.8.2-0ubuntu2).
python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Collecting git+https://github.com/patrikoss/direct_redis.git
  Cloning https://github.com/patrikoss/direct_redis.git to /tmp/pip-req-build-boa0fi1j
  Running command git clone -q https://github.com/patrikoss/direct_redis.git /tmp/pip-req-build-boa0fi1j
[31m  ERROR: Error [Errno 2] No such file or directory: 'git' while executing command git clone -q https://github.com/patrikoss/direct_redis.git /tmp/pip-req-build-boa0fi1j[0m
[31mERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?[0m
Running /platform/source/s01/v4_engoff/m22221111/m22221111_q16_t0.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct-redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
python: can't open file 'python_code.py': [Errno 2] No such file or directory
Running /platform/source/s01/v4_engoff/m22221111/m22221111_q17_t0.sh
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt install python3.8-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']

/platform/source/s01/v4_engoff/m22221111/m22221111_q17_t0.sh: line 7: venv/bin/activate: No such file or directory
Collecting pip
  Downloading pip-23.3.1-py3-none-any.whl (2.1 MB)
[?25l[K     |▏                               | 10 kB 6.4 MB/s eta 0:00:01[K     |▎                               | 20 kB 6.8 MB/s eta 0:00:01[K     |▌                               | 30 kB 9.9 MB/s eta 0:00:01[K     |▋                               | 40 kB 4.5 MB/s eta 0:00:01[K     |▊                               | 51 kB 4.6 MB/s eta 0:00:01[K     |█                               | 61 kB 5.4 MB/s eta 0:00:01[K     |█                               | 71 kB 5.6 MB/s eta 0:00:01[K     |█▎                              | 81 kB 6.4 MB/s eta 0:00:01[K     |█▍                              | 92 kB 6.1 MB/s eta 0:00:01[K     |█▌                              | 102 kB 6.2 MB/s eta 0:00:01[K     |█▊                              | 112 kB 6.2 MB/s eta 0:00:01[K     |█▉                              | 122 kB 6.2 MB/s eta 0:00:01[K     |██                              | 133 kB 6.2 MB/s eta 0:00:01[K     |██▏                             | 143 kB 6.2 MB/s eta 0:00:01[K     |██▎                             | 153 kB 6.2 MB/s eta 0:00:01[K     |██▌                             | 163 kB 6.2 MB/s eta 0:00:01[K     |██▋                             | 174 kB 6.2 MB/s eta 0:00:01[K     |██▉                             | 184 kB 6.2 MB/s eta 0:00:01[K     |███                             | 194 kB 6.2 MB/s eta 0:00:01[K     |███                             | 204 kB 6.2 MB/s eta 0:00:01[K     |███▎                            | 215 kB 6.2 MB/s eta 0:00:01[K     |███▍                            | 225 kB 6.2 MB/s eta 0:00:01[K     |███▋                            | 235 kB 6.2 MB/s eta 0:00:01[K     |███▊                            | 245 kB 6.2 MB/s eta 0:00:01[K     |███▉                            | 256 kB 6.2 MB/s eta 0:00:01[K     |████                            | 266 kB 6.2 MB/s eta 0:00:01[K     |████▏                           | 276 kB 6.2 MB/s eta 0:00:01[K     |████▍                           | 286 kB 6.2 MB/s eta 0:00:01[K     |████▌                           | 296 kB 6.2 MB/s eta 0:00:01[K     |████▋                           | 307 kB 6.2 MB/s eta 0:00:01[K     |████▉                           | 317 kB 6.2 MB/s eta 0:00:01[K     |█████                           | 327 kB 6.2 MB/s eta 0:00:01[K     |█████▏                          | 337 kB 6.2 MB/s eta 0:00:01[K     |█████▎                          | 348 kB 6.2 MB/s eta 0:00:01[K     |█████▍                          | 358 kB 6.2 MB/s eta 0:00:01[K     |█████▋                          | 368 kB 6.2 MB/s eta 0:00:01[K     |█████▊                          | 378 kB 6.2 MB/s eta 0:00:01[K     |██████                          | 389 kB 6.2 MB/s eta 0:00:01[K     |██████                          | 399 kB 6.2 MB/s eta 0:00:01[K     |██████▏                         | 409 kB 6.2 MB/s eta 0:00:01[K     |██████▍                         | 419 kB 6.2 MB/s eta 0:00:01[K     |██████▌                         | 430 kB 6.2 MB/s eta 0:00:01[K     |██████▊                         | 440 kB 6.2 MB/s eta 0:00:01[K     |██████▉                         | 450 kB 6.2 MB/s eta 0:00:01[K     |███████                         | 460 kB 6.2 MB/s eta 0:00:01[K     |███████▏                        | 471 kB 6.2 MB/s eta 0:00:01[K     |███████▎                        | 481 kB 6.2 MB/s eta 0:00:01[K     |███████▌                        | 491 kB 6.2 MB/s eta 0:00:01[K     |███████▋                        | 501 kB 6.2 MB/s eta 0:00:01[K     |███████▊                        | 512 kB 6.2 MB/s eta 0:00:01[K     |████████                        | 522 kB 6.2 MB/s eta 0:00:01[K     |████████                        | 532 kB 6.2 MB/s eta 0:00:01[K     |████████▎                       | 542 kB 6.2 MB/s eta 0:00:01[K     |████████▍                       | 552 kB 6.2 MB/s eta 0:00:01[K     |████████▌                       | 563 kB 6.2 MB/s eta 0:00:01[K     |████████▊                       | 573 kB 6.2 MB/s eta 0:00:01[K     |████████▉                       | 583 kB 6.2 MB/s eta 0:00:01[K     |█████████                       | 593 kB 6.2 MB/s eta 0:00:01[K     |█████████▏                      | 604 kB 6.2 MB/s eta 0:00:01[K     |█████████▎                      | 614 kB 6.2 MB/s eta 0:00:01[K     |█████████▌                      | 624 kB 6.2 MB/s eta 0:00:01[K     |█████████▋                      | 634 kB 6.2 MB/s eta 0:00:01[K     |█████████▉                      | 645 kB 6.2 MB/s eta 0:00:01[K     |██████████                      | 655 kB 6.2 MB/s eta 0:00:01[K     |██████████                      | 665 kB 6.2 MB/s eta 0:00:01[K     |██████████▎                     | 675 kB 6.2 MB/s eta 0:00:01[K     |██████████▍                     | 686 kB 6.2 MB/s eta 0:00:01[K     |██████████▋                     | 696 kB 6.2 MB/s eta 0:00:01[K     |██████████▊                     | 706 kB 6.2 MB/s eta 0:00:01[K     |██████████▉                     | 716 kB 6.2 MB/s eta 0:00:01[K     |███████████                     | 727 kB 6.2 MB/s eta 0:00:01[K     |███████████▏                    | 737 kB 6.2 MB/s eta 0:00:01[K     |███████████▍                    | 747 kB 6.2 MB/s eta 0:00:01[K     |███████████▌                    | 757 kB 6.2 MB/s eta 0:00:01[K     |███████████▋                    | 768 kB 6.2 MB/s eta 0:00:01[K     |███████████▉                    | 778 kB 6.2 MB/s eta 0:00:01[K     |████████████                    | 788 kB 6.2 MB/s eta 0:00:01[K     |████████████▏                   | 798 kB 6.2 MB/s eta 0:00:01[K     |████████████▎                   | 808 kB 6.2 MB/s eta 0:00:01[K     |████████████▍                   | 819 kB 6.2 MB/s eta 0:00:01[K     |████████████▋                   | 829 kB 6.2 MB/s eta 0:00:01[K     |████████████▊                   | 839 kB 6.2 MB/s eta 0:00:01[K     |█████████████                   | 849 kB 6.2 MB/s eta 0:00:01[K     |█████████████                   | 860 kB 6.2 MB/s eta 0:00:01[K     |█████████████▏                  | 870 kB 6.2 MB/s eta 0:00:01[K     |█████████████▍                  | 880 kB 6.2 MB/s eta 0:00:01[K     |█████████████▌                  | 890 kB 6.2 MB/s eta 0:00:01[K     |█████████████▊                  | 901 kB 6.2 MB/s eta 0:00:01[K     |█████████████▉                  | 911 kB 6.2 MB/s eta 0:00:01[K     |██████████████                  | 921 kB 6.2 MB/s eta 0:00:01[K     |██████████████▏                 | 931 kB 6.2 MB/s eta 0:00:01[K     |██████████████▎                 | 942 kB 6.2 MB/s eta 0:00:01[K     |██████████████▌                 | 952 kB 6.2 MB/s eta 0:00:01[K     |██████████████▋                 | 962 kB 6.2 MB/s eta 0:00:01[K     |██████████████▊                 | 972 kB 6.2 MB/s eta 0:00:01[K     |███████████████                 | 983 kB 6.2 MB/s eta 0:00:01[K     |███████████████                 | 993 kB 6.2 MB/s eta 0:00:01[K     |███████████████▎                | 1.0 MB 6.2 MB/s eta 0:00:01[K     |███████████████▍                | 1.0 MB 6.2 MB/s eta 0:00:01[K     |███████████████▌                | 1.0 MB 6.2 MB/s eta 0:00:01[K     |███████████████▊                | 1.0 MB 6.2 MB/s eta 0:00:01[K     |███████████████▉                | 1.0 MB 6.2 MB/s eta 0:00:01[K     |████████████████                | 1.1 MB 6.2 MB/s eta 0:00:01[K     |████████████████▏               | 1.1 MB 6.2 MB/s eta 0:00:01[K     |████████████████▎               | 1.1 MB 6.2 MB/s eta 0:00:01[K     |████████████████▌               | 1.1 MB 6.2 MB/s eta 0:00:01[K     |████████████████▋               | 1.1 MB 6.2 MB/s eta 0:00:01[K     |████████████████▉               | 1.1 MB 6.2 MB/s eta 0:00:01[K     |█████████████████               | 1.1 MB 6.2 MB/s eta 0:00:01[K     |█████████████████               | 1.1 MB 6.2 MB/s eta 0:00:01[K     |█████████████████▎              | 1.1 MB 6.2 MB/s eta 0:00:01[K     |█████████████████▍              | 1.1 MB 6.2 MB/s eta 0:00:01[K     |█████████████████▋              | 1.2 MB 6.2 MB/s eta 0:00:01[K     |█████████████████▊              | 1.2 MB 6.2 MB/s eta 0:00:01[K     |█████████████████▉              | 1.2 MB 6.2 MB/s eta 0:00:01[K     |██████████████████              | 1.2 MB 6.2 MB/s eta 0:00:01[K     |██████████████████▏             | 1.2 MB 6.2 MB/s eta 0:00:01[K     |██████████████████▍             | 1.2 MB 6.2 MB/s eta 0:00:01[K     |██████████████████▌             | 1.2 MB 6.2 MB/s eta 0:00:01[K     |██████████████████▋             | 1.2 MB 6.2 MB/s eta 0:00:01[K     |██████████████████▉             | 1.2 MB 6.2 MB/s eta 0:00:01[K     |███████████████████             | 1.2 MB 6.2 MB/s eta 0:00:01[K     |███████████████████▏            | 1.3 MB 6.2 MB/s eta 0:00:01[K     |███████████████████▎            | 1.3 MB 6.2 MB/s eta 0:00:01[K     |███████████████████▍            | 1.3 MB 6.2 MB/s eta 0:00:01[K     |███████████████████▋            | 1.3 MB 6.2 MB/s eta 0:00:01[K     |███████████████████▊            | 1.3 MB 6.2 MB/s eta 0:00:01[K     |████████████████████            | 1.3 MB 6.2 MB/s eta 0:00:01[K     |████████████████████            | 1.3 MB 6.2 MB/s eta 0:00:01[K     |████████████████████▏           | 1.3 MB 6.2 MB/s eta 0:00:01[K     |████████████████████▍           | 1.3 MB 6.2 MB/s eta 0:00:01[K     |████████████████████▌           | 1.4 MB 6.2 MB/s eta 0:00:01[K     |████████████████████▊           | 1.4 MB 6.2 MB/s eta 0:00:01[K     |████████████████████▉           | 1.4 MB 6.2 MB/s eta 0:00:01[K     |█████████████████████           | 1.4 MB 6.2 MB/s eta 0:00:01[K     |█████████████████████▏          | 1.4 MB 6.2 MB/s eta 0:00:01[K     |█████████████████████▎          | 1.4 MB 6.2 MB/s eta 0:00:01[K     |█████████████████████▌          | 1.4 MB 6.2 MB/s eta 0:00:01[K     |█████████████████████▋          | 1.4 MB 6.2 MB/s eta 0:00:01[K     |█████████████████████▊          | 1.4 MB 6.2 MB/s eta 0:00:01[K     |██████████████████████          | 1.4 MB 6.2 MB/s eta 0:00:01[K     |██████████████████████          | 1.5 MB 6.2 MB/s eta 0:00:01[K     |██████████████████████▎         | 1.5 MB 6.2 MB/s eta 0:00:01[K     |██████████████████████▍         | 1.5 MB 6.2 MB/s eta 0:00:01[K     |██████████████████████▌         | 1.5 MB 6.2 MB/s eta 0:00:01[K     |██████████████████████▊         | 1.5 MB 6.2 MB/s eta 0:00:01[K     |██████████████████████▉         | 1.5 MB 6.2 MB/s eta 0:00:01[K     |███████████████████████         | 1.5 MB 6.2 MB/s eta 0:00:01[K     |███████████████████████▏        | 1.5 MB 6.2 MB/s eta 0:00:01[K     |███████████████████████▎        | 1.5 MB 6.2 MB/s eta 0:00:01[K     |███████████████████████▌        | 1.5 MB 6.2 MB/s eta 0:00:01[K     |███████████████████████▋        | 1.6 MB 6.2 MB/s eta 0:00:01[K     |███████████████████████▉        | 1.6 MB 6.2 MB/s eta 0:00:01[K     |████████████████████████        | 1.6 MB 6.2 MB/s eta 0:00:01[K     |████████████████████████        | 1.6 MB 6.2 MB/s eta 0:00:01[K     |████████████████████████▎       | 1.6 MB 6.2 MB/s eta 0:00:01[K     |████████████████████████▍       | 1.6 MB 6.2 MB/s eta 0:00:01[K     |████████████████████████▋       | 1.6 MB 6.2 MB/s eta 0:00:01[K     |████████████████████████▊       | 1.6 MB 6.2 MB/s eta 0:00:01[K     |████████████████████████▉       | 1.6 MB 6.2 MB/s eta 0:00:01[K     |█████████████████████████       | 1.6 MB 6.2 MB/s eta 0:00:01[K     |█████████████████████████▏      | 1.7 MB 6.2 MB/s eta 0:00:01[K     |█████████████████████████▍      | 1.7 MB 6.2 MB/s eta 0:00:01[K     |█████████████████████████▌      | 1.7 MB 6.2 MB/s eta 0:00:01[K     |█████████████████████████▋      | 1.7 MB 6.2 MB/s eta 0:00:01[K     |█████████████████████████▉      | 1.7 MB 6.2 MB/s eta 0:00:01[K     |██████████████████████████      | 1.7 MB 6.2 MB/s eta 0:00:01[K     |██████████████████████████▏     | 1.7 MB 6.2 MB/s eta 0:00:01[K     |██████████████████████████▎     | 1.7 MB 6.2 MB/s eta 0:00:01[K     |██████████████████████████▍     | 1.7 MB 6.2 MB/s eta 0:00:01[K     |██████████████████████████▋     | 1.8 MB 6.2 MB/s eta 0:00:01[K     |██████████████████████████▊     | 1.8 MB 6.2 MB/s eta 0:00:01[K     |███████████████████████████     | 1.8 MB 6.2 MB/s eta 0:00:01[K     |███████████████████████████     | 1.8 MB 6.2 MB/s eta 0:00:01[K     |███████████████████████████▏    | 1.8 MB 6.2 MB/s eta 0:00:01[K     |███████████████████████████▍    | 1.8 MB 6.2 MB/s eta 0:00:01[K     |███████████████████████████▌    | 1.8 MB 6.2 MB/s eta 0:00:01[K     |███████████████████████████▊    | 1.8 MB 6.2 MB/s eta 0:00:01[K     |███████████████████████████▉    | 1.8 MB 6.2 MB/s eta 0:00:01[K     |████████████████████████████    | 1.8 MB 6.2 MB/s eta 0:00:01[K     |████████████████████████████▏   | 1.9 MB 6.2 MB/s eta 0:00:01[K     |████████████████████████████▎   | 1.9 MB 6.2 MB/s eta 0:00:01[K     |████████████████████████████▌   | 1.9 MB 6.2 MB/s eta 0:00:01[K     |████████████████████████████▋   | 1.9 MB 6.2 MB/s eta 0:00:01[K     |████████████████████████████▊   | 1.9 MB 6.2 MB/s eta 0:00:01[K     |█████████████████████████████   | 1.9 MB 6.2 MB/s eta 0:00:01[K     |█████████████████████████████   | 1.9 MB 6.2 MB/s eta 0:00:01[K     |█████████████████████████████▎  | 1.9 MB 6.2 MB/s eta 0:00:01[K     |█████████████████████████████▍  | 1.9 MB 6.2 MB/s eta 0:00:01[K     |█████████████████████████████▌  | 1.9 MB 6.2 MB/s eta 0:00:01[K     |█████████████████████████████▊  | 2.0 MB 6.2 MB/s eta 0:00:01[K     |█████████████████████████████▉  | 2.0 MB 6.2 MB/s eta 0:00:01[K     |██████████████████████████████  | 2.0 MB 6.2 MB/s eta 0:00:01[K     |██████████████████████████████▏ | 2.0 MB 6.2 MB/s eta 0:00:01[K     |██████████████████████████████▎ | 2.0 MB 6.2 MB/s eta 0:00:01[K     |██████████████████████████████▌ | 2.0 MB 6.2 MB/s eta 0:00:01[K     |██████████████████████████████▋ | 2.0 MB 6.2 MB/s eta 0:00:01[K     |██████████████████████████████▉ | 2.0 MB 6.2 MB/s eta 0:00:01[K     |███████████████████████████████ | 2.0 MB 6.2 MB/s eta 0:00:01[K     |███████████████████████████████ | 2.0 MB 6.2 MB/s eta 0:00:01[K     |███████████████████████████████▎| 2.1 MB 6.2 MB/s eta 0:00:01[K     |███████████████████████████████▍| 2.1 MB 6.2 MB/s eta 0:00:01[K     |███████████████████████████████▋| 2.1 MB 6.2 MB/s eta 0:00:01[K     |███████████████████████████████▊| 2.1 MB 6.2 MB/s eta 0:00:01[K     |███████████████████████████████▉| 2.1 MB 6.2 MB/s eta 0:00:01[K     |████████████████████████████████| 2.1 MB 6.2 MB/s 
[?25hInstalling collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.0.2
    Not uninstalling pip at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'pip'. No files were found to uninstall.
Successfully installed pip-23.3.1
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: redis in /usr/local/lib/python3.8/dist-packages (3.4.1)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
chmod: cannot access 'query_code.py': No such file or directory
/platform/source/s01/v4_engoff/m22221111/m22221111_q17_t0.sh: line 19: deactivate: command not found
Running /platform/source/s01/v4_engoff/m22221111/m22221111_q18_t0.sh
/platform/source/s01/v4_engoff/m22221111/m22221111_q18_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_engoff/m22221111/m22221111_q18_t0.sh: line 7: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4_engoff/m22221111/m22221111_q19_t0.sh
/platform/source/s01/v4_engoff/m22221111/m22221111_q19_t0.sh: line 6: sudo: command not found
/platform/source/s01/v4_engoff/m22221111/m22221111_q19_t0.sh: line 7: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: redis in /usr/local/lib/python3.8/dist-packages (3.4.1)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mpython3: can't open file 'discounted_revenue_query.py': [Errno 2] No such file or directory
Running /platform/source/s01/v4_engoff/m22221111/m22221111_q1_t0.sh
/platform/source/s01/v4_engoff/m22221111/m22221111_q1_t0.sh: line 5: sudo: command not found
/platform/source/s01/v4_engoff/m22221111/m22221111_q1_t0.sh: line 8: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4_engoff/m22221111/m22221111_q20_t0.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4_engoff/m22221111/m22221111_q21_t0.sh
/platform/source/s01/v4_engoff/m22221111/m22221111_q21_t0.sh: line 5: sudo: command not found
/platform/source/s01/v4_engoff/m22221111/m22221111_q21_t0.sh: line 8: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRequirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct-redis) (3.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4_engoff/m22221111/m22221111_q22_t0.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4_engoff/m22221111/m22221111_q2_t0.sh
/platform/source/s01/v4_engoff/m22221111/m22221111_q2_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_engoff/m22221111/m22221111_q2_t0.sh: line 7: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct-redis) (3.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4_engoff/m22221111/m22221111_q3_t0.sh
/platform/source/s01/v4_engoff/m22221111/m22221111_q3_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_engoff/m22221111/m22221111_q3_t0.sh: line 7: sudo: command not found
Requirement already satisfied: pip in /usr/local/lib/python3.8/dist-packages (23.3.1)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRequirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4_engoff/m22221111/m22221111_q4_t0.sh
/platform/source/s01/v4_engoff/m22221111/m22221111_q4_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_engoff/m22221111/m22221111_q4_t0.sh: line 7: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4_engoff/m22221111/m22221111_q5_t0.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4_engoff/m22221111/m22221111_q6_t0.sh
Running /platform/source/s01/v4_engoff/m22221111/m22221111_q7_t0.sh
/platform/source/s01/v4_engoff/m22221111/m22221111_q7_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_engoff/m22221111/m22221111_q7_t0.sh: line 7: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRequirement already satisfied: redis in /usr/local/lib/python3.8/dist-packages (3.4.1)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRequirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mCollecting msgpack-python
  Downloading msgpack-python-0.5.6.tar.gz (138 kB)
[?25l     [90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[0m [32m0.0/139.0 kB[0m [31m?[0m eta [36m-:--:--[0m[2K     [90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[0m [32m139.0/139.0 kB[0m [31m6.4 MB/s[0m eta [36m0:00:00[0m
[?25h  Preparing metadata (setup.py) ... [?25l- done
[?25hBuilding wheels for collected packages: msgpack-python
  Building wheel for msgpack-python (setup.py) ... [?25l- \ | / - done
[?25h  Created wheel for msgpack-python: filename=msgpack_python-0.5.6-cp38-cp38-linux_aarch64.whl size=446757 sha256=0a5f2ca9bb31afda3b707acc8178bfc2ce83db688a45c717b25dcacba5e677ab
  Stored in directory: /root/.cache/pip/wheels/03/7f/e7/8ec405fe5220fe1401be3dfa943f6e1f10b525f54f68d75e0a
Successfully built msgpack-python
Installing collected packages: msgpack-python
Successfully installed msgpack-python-0.5.6
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4_engoff/m22221111/m22221111_q8_t0.sh
/platform/source/s01/v4_engoff/m22221111/m22221111_q8_t0.sh: line 6: sudo: command not found
/platform/source/s01/v4_engoff/m22221111/m22221111_q8_t0.sh: line 9: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct-redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRunning /platform/source/s01/v4_engoff/m22221111/m22221111_q9_t0.sh
/platform/source/s01/v4_engoff/m22221111/m22221111_q9_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4_engoff/m22221111/m22221111_q9_t0.sh: line 7: sudo: command not found
/platform/source/s01/v4_engoff/m22221111/m22221111_q9_t0.sh: line 10: sudo: command not found
/platform/source/s01/v4_engoff/m22221111/m22221111_q9_t0.sh: line 13: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRequirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mRequirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
[0mpython /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m22221111/m22221111_q10_t0.py /platform/output/s01/v4_engoff/m22221111/m22221111_q10_t0.csv /platform/expected/s01/q10.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m22221111/m22221111_q10_t0.py", line 32, in <module>
    nation = get_redis_data()
  File "/platform/source/s01/v4_engoff/m22221111/m22221111_q10_t0.py", line 24, in get_redis_data
    nation = pd.read_json(nation_data)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m22221111/m22221111_q11_t0.py /platform/output/s01/v4_engoff/m22221111/m22221111_q11_t0.csv /platform/expected/s01/q11.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m22221111/m22221111_q11_t0.py", line 17, in <module>
    nation = pd.read_json(nation_raw)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m22221111/m22221111_q12_t0.py /platform/output/s01/v4_engoff/m22221111/m22221111_q12_t0.csv /platform/expected/s01/q12.csv
>>> Expected ((2, 3))
   HIGH_LINE_COUNT  LOW_LINE_COUNT L_SHIPMODE
0              647             945       MAIL
1              620             943       SHIP

>>> Actual ((2, 3))
   late_order_count_non_priority  late_order_count_priority ship_mode
0                              0                          0      MAIL
1                              0                          0      SHIP

Head row similarity: 0.5260115606936416
Score.fail_wrong_output
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m22221111/m22221111_q13_t0.py /platform/output/s01/v4_engoff/m22221111/m22221111_q13_t0.csv /platform/expected/s01/q13.csv
>>> Expected ((37, 2))
    CUSTDIST  C_COUNT
0       5000        0
1        676       10
2        651        9
3        618       11
4        554       12
5        548        8
6        514       13
7        487        7
8        485       19
9        461       18
10       454       14
11       444       20
12       442       16
13       438       17
14       430       15
15       396       21
16       378       22
17       355        6
18       322       23
19       262       24
20       188       25
21       184        5
22       162       26
23       138       27
24       103       28
25        92        4
26        59       29
27        49        3
28        29       30
29        26       31
30        19       32
31        12        2
32         8       33
33         7       34
34         5       35
35         3        1
36         1       36

>>> Actual ((34, 2))
    customer_count  num_orders
0             5002           0
1               18           1
2               51           2
3              164           3
4              361           4
5              525           5
6              684           6
7              757           7
8              764           8
9              732           9
10             664          10
11             607          11
12             594          12
13             544          13
14             578          14
15             506          15
16             513          16
17             450          17
18             383          18
19             324          19
20             244          20
21             195          21
22             127          22
23              77          23
24              65          24
25              35          25
26              15          26
27               8          27
28               7          28
29               2          29
30               1          30
31               1          31
32               1          32
33               1          34

Score.fail_wrong_output
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m22221111/m22221111_q14_t0.py /platform/output/s01/v4_engoff/m22221111/m22221111_q14_t0.csv /platform/expected/s01/q14.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m22221111/m22221111_q14_t0.py", line 39, in <module>
    part_df = part_df.astype({
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/generic.py", line 6290, in astype
    raise KeyError(
KeyError: "Only a column name can be used for the key in a dtype mappings argument. 'P_PARTKEY' not found in columns."
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m22221111/m22221111_q15_t0.py /platform/output/s01/v4_engoff/m22221111/m22221111_q15_t0.csv /platform/expected/s01/q15.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m22221111/m22221111_q15_t0.py", line 43, in <module>
    main()
  File "/platform/source/s01/v4_engoff/m22221111/m22221111_q15_t0.py", line 30, in main
    if suppliers_json:
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/generic.py", line 1466, in __nonzero__
    raise ValueError(
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m22221111/m22221111_q16_t0.py /platform/output/s01/v4_engoff/m22221111/m22221111_q16_t0.csv /platform/expected/s01/q16.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m22221111/m22221111_q16_t0.py", line 24, in <module>
    part_df = get_redis_data('part')
  File "/platform/source/s01/v4_engoff/m22221111/m22221111_q16_t0.py", line 18, in get_redis_data
    return pd.read_json(data) if data else pd.DataFrame()
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/generic.py", line 1466, in __nonzero__
    raise ValueError(
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m22221111/m22221111_q17_t0.py /platform/output/s01/v4_engoff/m22221111/m22221111_q17_t0.csv /platform/expected/s01/q17.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m22221111/m22221111_q17_t0.py", line 16, in <module>
    part_df = pd.read_json(part_df_json)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m22221111/m22221111_q18_t0.py /platform/output/s01/v4_engoff/m22221111/m22221111_q18_t0.csv /platform/expected/s01/q18.csv
Score.fail_timeout
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m22221111/m22221111_q19_t0.py /platform/output/s01/v4_engoff/m22221111/m22221111_q19_t0.csv /platform/expected/s01/q19.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m22221111/m22221111_q19_t0.py", line 23, in <module>
    part_data = pd.read_json(redis.get('part'), typ='series').to_frame().transpose()
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m22221111/m22221111_q1_t0.py /platform/output/s01/v4_engoff/m22221111/m22221111_q1_t0.csv /platform/expected/s01/q1.csv
Query results have been written to query_output.csv
>>> Expected ((4, 10))
   AVG_DISC     AVG_PRICE    AVG_QTY  COUNT_ORDER L_LINESTATUS L_RETURNFLAG  SUM_BASE_PRICE    SUM_CHARGE  SUM_DISC_PRICE  SUM_QTY
0  0.050145  36002.123829  25.537587       147790            F            A    5.320754e+09  5.256751e+09    5.054096e+09  3774200
1  0.049394  35521.326916  25.300664         3765            F            N    1.337378e+08  1.322863e+08    1.271324e+08    95257
2  0.050096  36000.924688  25.545538       292000            O            N    1.051227e+10  1.038558e+10    9.986238e+09  7459297
3  0.049989  35994.029214  25.525944       148301            F            R    5.337951e+09  5.274406e+09    5.071819e+09  3785523

>>> Actual ((0, 10))
Empty DataFrame
Columns: [AVG_DISC, AVG_PRICE, AVG_QTY, COUNT_ORDER, L_LINESTATUS, L_RETURNFLAG, SUM_BASE_PRICE, SUM_CHARGE, SUM_DISC_PRICE, SUM_QTY]
Index: []

Score.fail_wrong_output
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m22221111/m22221111_q20_t0.py /platform/output/s01/v4_engoff/m22221111/m22221111_q20_t0.csv /platform/expected/s01/q20.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m22221111/m22221111_q20_t0.py", line 25, in <module>
    nation_df = pd.DataFrame(eval(redis_client.get('nation')))
TypeError: eval() arg 1 must be a string, bytes or code object
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m22221111/m22221111_q21_t0.py /platform/output/s01/v4_engoff/m22221111/m22221111_q21_t0.csv /platform/expected/s01/q21.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m22221111/m22221111_q21_t0.py", line 21, in <module>
    nation = pd.read_json(redis_conn.get('nation'))  # Assuming the data is stored as JSON string
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m22221111/m22221111_q22_t0.py /platform/output/s01/v4_engoff/m22221111/m22221111_q22_t0.csv /platform/expected/s01/q22.csv
>>> Expected ((4, 3))
   CNTRYCODE  NUMCUST  TOTACCTBAL
0         20       91   666158.10
1         21      101   760953.55
2         22      106   759804.81
3         30       87   646748.02

>>> Actual ((0, 3))
Empty DataFrame
Columns: [AverageBalance, CountryCode, CustomerCount]
Index: []

Score.fail_wrong_output
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m22221111/m22221111_q2_t0.py /platform/output/s01/v4_engoff/m22221111/m22221111_q2_t0.csv /platform/expected/s01/q2.csv
>>> Expected ((44, 8))
            N_NAME          P_MFGR  P_PARTKEY  S_ACCTBAL                                 S_ADDRESS                                          S_COMMENT              S_NAME          S_PHONE
0   UNITED KINGDOM  Manufacturer#5      13120    9828.21                              x5U7MBZmwfG9             s the slyly even ideas poach fluffily   Supplier#000000647  33-258-202-4782
1           FRANCE  Manufacturer#1       3563    9508.37         INWNH2w,OOWgNDq0BRCcBwOMQc6PdFDc4  ests sleep quickly express ideas. ironic ideas...  Supplier#000000070  16-821-608-1166
2           FRANCE  Manufacturer#4      17268    9508.37         INWNH2w,OOWgNDq0BRCcBwOMQc6PdFDc4  ests sleep quickly express ideas. ironic ideas...  Supplier#000000070  16-821-608-1166
3          ROMANIA  Manufacturer#5      10021    9453.01                  ,6HYXb4uaHITmtMBj4Ak57Pd  gular frets. permanently special multipliers b...  Supplier#000000802  29-342-882-6463
4          ROMANIA  Manufacturer#4      13275    9453.01                  ,6HYXb4uaHITmtMBj4Ak57Pd  gular frets. permanently special multipliers b...  Supplier#000000802  29-342-882-6463
5   UNITED KINGDOM  Manufacturer#1      13325    9192.10            nJ 2t0f7Ve,wL1,6WzGBJLNBUCKlsV  es across the carefully express accounts boost...  Supplier#000000115  33-597-248-1220
6          GERMANY  Manufacturer#4       4958    9032.15                            8grA EHBnwOZhO                      nding dependencies nag furiou  Supplier#000000959  17-108-642-3106
7           RUSSIA  Manufacturer#3      11810    8702.02           MaVf XgwPdkiX4nfJGOis8Uu2zKiIZH  oss the deposits cajole carefully even pinto b...  Supplier#000000333  32-508-202-6136
8           FRANCE  Manufacturer#2      10551    8615.50         8qh4tezyScl5bidLAysvutB,,ZI2dn6xP  y quickly regular deposits? quickly pending pa...  Supplier#000000812  16-585-724-6633
9           FRANCE  Manufacturer#4      13811    8615.50         8qh4tezyScl5bidLAysvutB,,ZI2dn6xP  y quickly regular deposits? quickly pending pa...  Supplier#000000812  16-585-724-6633
10          RUSSIA  Manufacturer#4       6854    8488.53                           E Sv9brQVf43Mzz  ages. carefully final excuses nag finally. car...  Supplier#000000367  32-458-198-9557
11          FRANCE  Manufacturer#3      11384    8430.52       IUzsmT,2oBgjhWP2TlXTL6IkJH,4h,1SJRt  ites among the always final ideas kindle accor...  Supplier#000000646  16-601-220-5489
12          RUSSIA  Manufacturer#5       4637    8271.39               rBDNgCr04x0sfdzD5,gFOutCiG2  s cajole quickly special requests. quickly ent...  Supplier#000000146  32-792-619-3155
13          RUSSIA  Manufacturer#4        323    8096.98               2O8 sy9g2mlBOuEjzj0pA2pevk,  ully after the regular requests. slyly final d...  Supplier#000000574  32-866-246-8752
14  UNITED KINGDOM  Manufacturer#2       7655    7392.78                          RtsXQ,SunkA XHy9                   ake carefully across the quickly  Supplier#000000170  33-803-340-5398
15         GERMANY  Manufacturer#5      10956    7205.20                  VtaNKN5Mqui5yh7j2ldd5waf   excuses wake express deposits. furiously care...  Supplier#000000477  17-180-144-7991
16  UNITED KINGDOM  Manufacturer#5      13217    6820.35                     s,4TicNGB4uO6PaSqNBUq  s unwind silently furiously regular courts. fi...  Supplier#000000007  33-990-965-2201
17          FRANCE  Manufacturer#3       4191    6721.70                          P3O5p UFz1QsLmZX                   ect blithely blithely final acco  Supplier#000000954  16-537-341-8517
18         GERMANY  Manufacturer#2      10735    6329.90                      Wx4dQwOAwWjfSCGupfrM                 ironic forges cajole blithely agai  Supplier#000000996  17-447-811-3282
19          RUSSIA  Manufacturer#1      18139    6173.87                qcor1u,vJXAokjnL5,dilyYNmh  blithely pending packages cajole furiously sly...  Supplier#000000408  32-858-724-2950
20          RUSSIA  Manufacturer#4      13784    5364.99  W VkHBpQyD3qjQjWGpWicOpmILFehmEdWy67kUGY      packages boost carefully. express ideas along  Supplier#000000785  32-297-653-2203
21         GERMANY  Manufacturer#1      16327    5069.27                               SMm24d WG62           he unusual ideas. slyly final packages a  Supplier#000000328  17-231-513-5721
22         ROMANIA  Manufacturer#5       7320    4941.88                           pLngFl5yeMcHyov                         y final requests impress s  Supplier#000000321  29-573-279-1406
23          RUSSIA  Manufacturer#1      12238    4672.25   XO101kgHrJagK2FL1U6QCaTE ncCsMbeuTgK6o8  arls wake furiously deposits. even, regular depen  Supplier#000000239  32-396-654-6826
24          RUSSIA  Manufacturer#3       5679    4586.49     UhvDfdEfJh,Qbe7VZb8uSGO2TU 0jEa6nXZXE   the regularly regular dependencies. carefully...  Supplier#000000680  32-522-382-1620
25          FRANCE  Manufacturer#5      18344    4518.31                  pVyWsjOidpHKp4NfKU4yLeym  ts detect along the foxes. final Tiresias are....  Supplier#000000149  16-660-553-2456
26          FRANCE  Manufacturer#2      18972    4315.15                                SF7dR8V5pK  ronic orbits are furiously across the requests...  Supplier#000000509  16-298-154-3365
27          FRANCE  Manufacturer#4       8036    3526.53                               a,liVofXbCJ                          lar dinos nag slyly brave  Supplier#000000553  16-599-552-3755
28          FRANCE  Manufacturer#3      17018    3526.53                               a,liVofXbCJ                          lar dinos nag slyly brave  Supplier#000000553  16-599-552-3755
29         GERMANY  Manufacturer#4       4841    3294.68                            KIFxV73eovmwhh  e slyly special foxes. furiously unusual depos...  Supplier#000000350  17-113-181-4017
30          RUSSIA  Manufacturer#4       1015    2972.26      YjP5C55zHDXL7LalK27zfQnwejdpin4AMpvh     ously express ideas haggle quickly dugouts? fu  Supplier#000000016  32-822-502-4215
31         ROMANIA  Manufacturer#2       3080    2963.09                              iYzUIypKhC0Y  eep blithely regular dependencies. blithely re...  Supplier#000000840  29-781-337-5584
32         ROMANIA  Manufacturer#2      13981    2221.25                        lwZ I15rq9kmZXUNhl  nal foxes eat slyly about the fluffily permane...  Supplier#000000771  29-986-304-9006
33          FRANCE  Manufacturer#3      18103    1381.97     Dcl4yGrzqv3OPeRO49bKh78XmQEDR7PBXIs0m  gular ideas. bravely bold deposits haggle thro...  Supplier#000000104  16-434-972-6922
34         ROMANIA  Manufacturer#4       8363     906.07   utbplAm g7RmxVfYoNdhcrQGWuzRqPe0qHSwbKw  ickly unusual requests cajole. accounts above ...  Supplier#000000138  29-533-434-6776
35          RUSSIA  Manufacturer#2      11276     765.69                             jwFN7ZB3T9sMF  nusual requests. furiously unusual epitaphs in...  Supplier#000000799  32-579-339-1495
36         ROMANIA  Manufacturer#3       6213     727.89        XckbzsAgBLbUkdfjgJEPjmUMTM8ebSMEvI  gular excuses. furiously regular excuses sleep...  Supplier#000000470  29-165-289-1523
37          RUSSIA  Manufacturer#4       4888     683.07                              oWekiBV6s,1g                    ly regular requests cajole abou  Supplier#000000651  32-181-426-4490
38          FRANCE  Manufacturer#1       2037     167.56                          6Bk06GVtwZaKqg01    the theodolites. ironic, ironic deposits above   Supplier#000000290  16-675-286-5102
39  UNITED KINGDOM  Manufacturer#2       9430      91.39     a,UE,6nRVl2fCphkOoetR1ajIzAEJ1Aa1G1HV       pinto beans. carefully express requests hagg  Supplier#000000949  33-332-697-2768
40         ROMANIA  Manufacturer#4      17242    -314.06             VmXQl ,vY8JiEseo8Mv4zscvNCfsY                    bold deposits. carefully even d  Supplier#000000510  29-207-852-3454
41         GERMANY  Manufacturer#5       2156    -820.89        LyXUYFz7aXrvy65kKAbTatGzGS,NDBcdtD   y final, slow theodolites. furiously regular req  Supplier#000000409  17-719-517-9836
42         ROMANIA  Manufacturer#5       9926    -845.44             hQvlBqbqqnA5Dgo1BffRBX78tkkRu                         ctions. carefully sly requ  Supplier#000000704  29-300-896-5991
43         GERMANY  Manufacturer#1       5797    -942.73                           Rc7U1cRUhYs03JD  slyly furiously final decoys; silent, special ...  Supplier#000000563  17-108-537-2691

>>> Actual ((0, 9))
Empty DataFrame
Columns: [N_NAME, PS_SUPPLYCOST, P_MFGR, P_PARTKEY, S_ACCTBAL, S_ADDRESS, S_COMMENT, S_NAME, S_PHONE]
Index: []

Score.fail_wrong_output
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m22221111/m22221111_q3_t0.py /platform/output/s01/v4_engoff/m22221111/m22221111_q3_t0.csv /platform/expected/s01/q3.csv
Score.fail_timeout
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m22221111/m22221111_q4_t0.py /platform/output/s01/v4_engoff/m22221111/m22221111_q4_t0.csv /platform/expected/s01/q4.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m22221111/m22221111_q4_t0.py", line 23, in <module>
    if late_lineitems.count() > 0:
AttributeError: 'Cursor' object has no attribute 'count'
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m22221111/m22221111_q5_t0.py /platform/output/s01/v4_engoff/m22221111/m22221111_q5_t0.csv /platform/expected/s01/q5.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m22221111/m22221111_q5_t0.py", line 23, in <module>
    nation_df = pd.read_json(redis_client.get("nation"), orient='records')
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m22221111/m22221111_q6_t0.py /platform/output/s01/v4_engoff/m22221111/m22221111_q6_t0.csv /platform/expected/s01/q6.csv
>>> Expected ((1, 1))
        REVENUE
0  7.115407e+06

>>> Actual ((1, 1))
   total_revenue_increase
0                       0

Head row similarity: 0.2682926829268293
Score.fail_wrong_output
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m22221111/m22221111_q7_t0.py /platform/output/s01/v4_engoff/m22221111/m22221111_q7_t0.csv /platform/expected/s01/q7.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m22221111/m22221111_q7_t0.py", line 21, in <module>
    nation_df = pd.read_msgpack(redis_client.get('nation'))
AttributeError: module 'pandas' has no attribute 'read_msgpack'
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m22221111/m22221111_q8_t0.py /platform/output/s01/v4_engoff/m22221111/m22221111_q8_t0.csv /platform/expected/s01/q8.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m22221111/m22221111_q8_t0.py", line 78, in <module>
    main()
  File "/platform/source/s01/v4_engoff/m22221111/m22221111_q8_t0.py", line 71, in main
    suppliers_asia_india = get_redis_data()
  File "/platform/source/s01/v4_engoff/m22221111/m22221111_q8_t0.py", line 40, in get_redis_data
    df_nation = pd.DataFrame(eval(redis_client.get('nation')))
TypeError: eval() arg 1 must be a string, bytes or code object
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4_engoff/m22221111/m22221111_q9_t0.py /platform/output/s01/v4_engoff/m22221111/m22221111_q9_t0.csv /platform/expected/s01/q9.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4_engoff/m22221111/m22221111_q9_t0.py", line 18, in <module>
    nation_df = pd.read_json(redis_client.get('nation'))
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
