Using MAPPING_STR=21212121, VERSION_DIR=v4
Running /platform/source/s01/v4/m21212121/m21212121_q10_t0.sh

0% [Working]
            
Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease

0% [Working]
            
Get:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease [114 kB]

0% [2 InRelease 1239 B/114 kB 1%]
0% [2 InRelease 15.7 kB/114 kB 14%]
                                   
0% [Working]
0% [Waiting for headers]
                        
Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease

                        
0% [Working]
0% [Waiting for headers]
                        
Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease

                        
0% [Working]
100% [Working]
              
Fetched 114 kB in 1s (130 kB/s)

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 60%

Reading package lists... 60%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 74%

Reading package lists... 74%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done


Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 60%

Reading package lists... 60%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 74%

Reading package lists... 74%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done


Building dependency tree... 0%

Building dependency tree... 0%

Building dependency tree... 50%

Building dependency tree... 50%

Building dependency tree       


Reading state information... 0%

Reading state information... 0%

Reading state information... Done


Calculating upgrade... 0%

Calculating upgrade... 50%

Calculating upgrade... Done

0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 60%

Reading package lists... 60%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 74%

Reading package lists... 74%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done


Building dependency tree... 0%

Building dependency tree... 0%

Building dependency tree... 50%

Building dependency tree... 50%

Building dependency tree       


Reading state information... 0%

Reading state information... 0%

Reading state information... Done

gcc is already the newest version (4:9.3.0-1ubuntu2).
gcc set to manually installed.
python3 is already the newest version (3.8.2-0ubuntu2).
python3 set to manually installed.
python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: redis in /usr/local/lib/python3.8/dist-packages (3.4.1)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4/m21212121/m21212121_q11_t0.sh

0% [Working]
            
Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease

0% [Working]
0% [Waiting for headers]
                        
Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease

                        
0% [Working]
0% [Waiting for headers]
                        
Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease

                        
0% [Working]
0% [Waiting for headers]
                        
Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease

                        
0% [Working]
20% [Working]
             

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 60%

Reading package lists... 60%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 74%

Reading package lists... 74%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done


Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 60%

Reading package lists... 60%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 74%

Reading package lists... 74%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done


Building dependency tree... 0%

Building dependency tree... 0%

Building dependency tree... 50%

Building dependency tree... 50%

Building dependency tree       


Reading state information... 0%

Reading state information... 0%

Reading state information... Done

python3 is already the newest version (3.8.2-0ubuntu2).
python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Collecting git+https://github.com/RedisJSON/redis-py.git
  Cloning https://github.com/RedisJSON/redis-py.git to /tmp/pip-req-build-c6bi36u3
  Running command git clone -q https://github.com/RedisJSON/redis-py.git /tmp/pip-req-build-c6bi36u3
[31m  ERROR: Error [Errno 2] No such file or directory: 'git' while executing command git clone -q https://github.com/RedisJSON/redis-py.git /tmp/pip-req-build-c6bi36u3[0m
[31mERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?[0m
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4/m21212121/m21212121_q12_t0.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4/m21212121/m21212121_q13_t0.sh
Running /platform/source/s01/v4/m21212121/m21212121_q14_t0.sh
Running /platform/source/s01/v4/m21212121/m21212121_q15_t0.sh
/platform/source/s01/v4/m21212121/m21212121_q15_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4/m21212121/m21212121_q15_t0.sh: line 7: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Running /platform/source/s01/v4/m21212121/m21212121_q16_t0.sh

0% [Working]
            
Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease

0% [Working]
0% [Waiting for headers]
                        
Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease

                        
0% [Working]
0% [Waiting for headers]
                        
Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease

                        
0% [Working]
0% [Waiting for headers]
                        
Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease

                        
0% [Working]
20% [Working]
             

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 60%

Reading package lists... 60%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 74%

Reading package lists... 74%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done


Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 60%

Reading package lists... 60%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 74%

Reading package lists... 74%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done


Building dependency tree... 0%

Building dependency tree... 0%

Building dependency tree... 50%

Building dependency tree... 50%

Building dependency tree       


Reading state information... 0%

Reading state information... 0%

Reading state information... Done

python3 is already the newest version (3.8.2-0ubuntu2).
python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: redis in /usr/local/lib/python3.8/dist-packages (3.4.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct-redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4/m21212121/m21212121_q17_t0.sh
/platform/source/s01/v4/m21212121/m21212121_q17_t0.sh: line 6: sudo: command not found
/platform/source/s01/v4/m21212121/m21212121_q17_t0.sh: line 7: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4/m21212121/m21212121_q18_t0.sh
Running /platform/source/s01/v4/m21212121/m21212121_q19_t0.sh
/platform/source/s01/v4/m21212121/m21212121_q19_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4/m21212121/m21212121_q19_t0.sh: line 5: sudo: command not found
/platform/source/s01/v4/m21212121/m21212121_q19_t0.sh: line 6: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Running /platform/source/s01/v4/m21212121/m21212121_q1_t0.sh

0% [Working]
            
Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease

0% [Working]
0% [Waiting for headers]
                        
Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease

0% [Waiting for headers]
                        
Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease

                        
0% [Working]
0% [Waiting for headers]
0% [Waiting for headers]
                        
Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease

                        
0% [Working]
20% [Working]
             

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 60%

Reading package lists... 60%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 74%

Reading package lists... 74%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done


Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 60%

Reading package lists... 60%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 74%

Reading package lists... 74%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done


Building dependency tree... 0%

Building dependency tree... 0%

Building dependency tree... 50%

Building dependency tree... 50%

Building dependency tree       


Reading state information... 0%

Reading state information... 0%

Reading state information... Done


Calculating upgrade... 0%

Calculating upgrade... 50%

Calculating upgrade... Done

0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 60%

Reading package lists... 60%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 74%

Reading package lists... 74%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done


Building dependency tree... 0%

Building dependency tree... 0%

Building dependency tree... 50%

Building dependency tree... 50%

Building dependency tree       


Reading state information... 0%

Reading state information... 0%

Reading state information... Done

python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Running /platform/source/s01/v4/m21212121/m21212121_q20_t0.sh
Running /platform/source/s01/v4/m21212121/m21212121_q21_t0.sh
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt install python3.8-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']

/platform/source/s01/v4/m21212121/m21212121_q21_t0.sh: line 7: venv/bin/activate: No such file or directory
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: redis in /usr/local/lib/python3.8/dist-packages (3.4.1)
Collecting msgpack
  Downloading msgpack-1.0.7-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (525 kB)
[?25l
[K     |▋                               | 10 kB 7.2 MB/s eta 0:00:01
[K     |█▎                              | 20 kB 9.0 MB/s eta 0:00:01
[K     |█▉                              | 30 kB 13.0 MB/s eta 0:00:01
[K     |██▌                             | 40 kB 3.8 MB/s eta 0:00:01
[K     |███▏                            | 51 kB 4.7 MB/s eta 0:00:01
[K     |███▊                            | 61 kB 5.6 MB/s eta 0:00:01
[K     |████▍                           | 71 kB 5.2 MB/s eta 0:00:01
[K     |█████                           | 81 kB 5.4 MB/s eta 0:00:01
[K     |█████▋                          | 92 kB 6.1 MB/s eta 0:00:01
[K     |██████▎                         | 102 kB 6.6 MB/s eta 0:00:01
[K     |██████▉                         | 112 kB 6.6 MB/s eta 0:00:01
[K     |███████▌                        | 122 kB 6.6 MB/s eta 0:00:01
[K     |████████                        | 133 kB 6.6 MB/s eta 0:00:01
[K     |████████▊                       | 143 kB 6.6 MB/s eta 0:00:01
[K     |█████████▍                      | 153 kB 6.6 MB/s eta 0:00:01
[K     |██████████                      | 163 kB 6.6 MB/s eta 0:00:01
[K     |██████████▋                     | 174 kB 6.6 MB/s eta 0:00:01
[K     |███████████▎                    | 184 kB 6.6 MB/s eta 0:00:01
[K     |███████████▉                    | 194 kB 6.6 MB/s eta 0:00:01
[K     |████████████▌                   | 204 kB 6.6 MB/s eta 0:00:01
[K     |█████████████                   | 215 kB 6.6 MB/s eta 0:00:01
[K     |█████████████▊                  | 225 kB 6.6 MB/s eta 0:00:01
[K     |██████████████▍                 | 235 kB 6.6 MB/s eta 0:00:01
[K     |███████████████                 | 245 kB 6.6 MB/s eta 0:00:01
[K     |███████████████▋                | 256 kB 6.6 MB/s eta 0:00:01
[K     |████████████████▏               | 266 kB 6.6 MB/s eta 0:00:01
[K     |████████████████▉               | 276 kB 6.6 MB/s eta 0:00:01
[K     |█████████████████▌              | 286 kB 6.6 MB/s eta 0:00:01
[K     |██████████████████              | 296 kB 6.6 MB/s eta 0:00:01
[K     |██████████████████▊             | 307 kB 6.6 MB/s eta 0:00:01
[K     |███████████████████▍            | 317 kB 6.6 MB/s eta 0:00:01
[K     |████████████████████            | 327 kB 6.6 MB/s eta 0:00:01
[K     |████████████████████▋           | 337 kB 6.6 MB/s eta 0:00:01
[K     |█████████████████████▏          | 348 kB 6.6 MB/s eta 0:00:01
[K     |█████████████████████▉          | 358 kB 6.6 MB/s eta 0:00:01
[K     |██████████████████████▌         | 368 kB 6.6 MB/s eta 0:00:01
[K     |███████████████████████         | 378 kB 6.6 MB/s eta 0:00:01
[K     |███████████████████████▊        | 389 kB 6.6 MB/s eta 0:00:01
[K     |████████████████████████▎       | 399 kB 6.6 MB/s eta 0:00:01
[K     |█████████████████████████       | 409 kB 6.6 MB/s eta 0:00:01
[K     |█████████████████████████▋      | 419 kB 6.6 MB/s eta 0:00:01
[K     |██████████████████████████▏     | 430 kB 6.6 MB/s eta 0:00:01
[K     |██████████████████████████▉     | 440 kB 6.6 MB/s eta 0:00:01
[K     |███████████████████████████▍    | 450 kB 6.6 MB/s eta 0:00:01
[K     |████████████████████████████    | 460 kB 6.6 MB/s eta 0:00:01
[K     |████████████████████████████▊   | 471 kB 6.6 MB/s eta 0:00:01
[K     |█████████████████████████████▎  | 481 kB 6.6 MB/s eta 0:00:01
[K     |██████████████████████████████  | 491 kB 6.6 MB/s eta 0:00:01
[K     |██████████████████████████████▋ | 501 kB 6.6 MB/s eta 0:00:01
[K     |███████████████████████████████▏| 512 kB 6.6 MB/s eta 0:00:01
[K     |███████████████████████████████▉| 522 kB 6.6 MB/s eta 0:00:01
[K     |████████████████████████████████| 525 kB 6.6 MB/s 
[?25hRequirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Installing collected packages: msgpack
Successfully installed msgpack-1.0.7
/platform/source/s01/v4/m21212121/m21212121_q21_t0.sh: line 13: deactivate: command not found
Running /platform/source/s01/v4/m21212121/m21212121_q22_t0.sh
/platform/source/s01/v4/m21212121/m21212121_q22_t0.sh: line 4: sudo: command not found
/platform/source/s01/v4/m21212121/m21212121_q22_t0.sh: line 5: sudo: command not found
/platform/source/s01/v4/m21212121/m21212121_q22_t0.sh: line 8: sudo: command not found
/platform/source/s01/v4/m21212121/m21212121_q22_t0.sh: line 8: wget: command not found
/platform/source/s01/v4/m21212121/m21212121_q22_t0.sh: line 9: sudo: command not found
/platform/source/s01/v4/m21212121/m21212121_q22_t0.sh: line 10: sudo: command not found
/platform/source/s01/v4/m21212121/m21212121_q22_t0.sh: line 11: sudo: command not found
/platform/source/s01/v4/m21212121/m21212121_q22_t0.sh: line 14: sudo: command not found
/platform/source/s01/v4/m21212121/m21212121_q22_t0.sh: line 15: sudo: command not found
/platform/source/s01/v4/m21212121/m21212121_q22_t0.sh: line 16: sudo: command not found
/platform/source/s01/v4/m21212121/m21212121_q22_t0.sh: line 17: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4/m21212121/m21212121_q2_t0.sh
/platform/source/s01/v4/m21212121/m21212121_q2_t0.sh: line 4: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: redis in /usr/local/lib/python3.8/dist-packages (3.4.1)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4/m21212121/m21212121_q3_t0.sh
/platform/source/s01/v4/m21212121/m21212121_q3_t0.sh: line 5: sudo: command not found
/platform/source/s01/v4/m21212121/m21212121_q3_t0.sh: line 6: sudo: command not found
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: redis in /usr/local/lib/python3.8/dist-packages (3.4.1)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4/m21212121/m21212121_q4_t0.sh

0% [Working]
            
Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease

0% [Working]
0% [Waiting for headers]
                        
Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease

                        
0% [Working]
0% [Waiting for headers]
                        
Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease

                        
0% [Working]
0% [Waiting for headers]
                        
Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease

                        
0% [Working]
20% [Working]
             

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 60%

Reading package lists... 60%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 74%

Reading package lists... 74%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done


Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 60%

Reading package lists... 60%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 74%

Reading package lists... 74%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done


Building dependency tree... 0%

Building dependency tree... 0%

Building dependency tree... 50%

Building dependency tree... 50%

Building dependency tree       


Reading state information... 0%

Reading state information... 0%

Reading state information... Done

python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4/m21212121/m21212121_q5_t0.sh
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt install python3.8-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']

/platform/source/s01/v4/m21212121/m21212121_q5_t0.sh: line 7: venv/bin/activate: No such file or directory
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
/platform/source/s01/v4/m21212121/m21212121_q5_t0.sh: line 13: deactivate: command not found
Running /platform/source/s01/v4/m21212121/m21212121_q6_t0.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Running /platform/source/s01/v4/m21212121/m21212121_q7_t0.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: redis in /usr/local/lib/python3.8/dist-packages (3.4.1)
Requirement already satisfied: direct_redis in /usr/local/lib/python3.8/dist-packages (0.3.1)
Requirement already satisfied: redis==3.4.1 in /usr/local/lib/python3.8/dist-packages (from direct_redis) (3.4.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4/m21212121/m21212121_q8_t0.sh

0% [Working]
            
Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease

0% [Working]
0% [Waiting for headers]
                        
Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease

                        
0% [Working]
0% [Waiting for headers]
                        
Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease

                        
0% [Working]
0% [Waiting for headers]
                        
Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease

                        
0% [Working]
20% [Working]
             

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 60%

Reading package lists... 60%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 74%

Reading package lists... 74%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done


Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 6%

Reading package lists... 60%

Reading package lists... 60%

Reading package lists... 61%

Reading package lists... 61%

Reading package lists... 74%

Reading package lists... 74%

Reading package lists... 75%

Reading package lists... 75%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 81%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 82%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 94%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done


Building dependency tree... 0%

Building dependency tree... 0%

Building dependency tree... 50%

Building dependency tree... 50%

Building dependency tree       


Reading state information... 0%

Reading state information... 0%

Reading state information... Done

python3 is already the newest version (3.8.2-0ubuntu2).
python3-pip is already the newest version (20.0.2-5ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Collecting git+https://github.com/20c/direct_redis.git
  Cloning https://github.com/20c/direct_redis.git to /tmp/pip-req-build-187kyn01
  Running command git clone -q https://github.com/20c/direct_redis.git /tmp/pip-req-build-187kyn01
[31m  ERROR: Error [Errno 2] No such file or directory: 'git' while executing command git clone -q https://github.com/20c/direct_redis.git /tmp/pip-req-build-187kyn01[0m
[31mERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?[0m
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Running /platform/source/s01/v4/m21212121/m21212121_q9_t0.sh
Requirement already satisfied: pymongo in /usr/local/lib/python3.8/dist-packages (4.6.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.8/dist-packages (from pymongo) (2.4.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (2.0.3)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.8/dist-packages (from pandas) (2023.3.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.20.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Collecting git+https://github.com/pbs/direct_redis.git
  Cloning https://github.com/pbs/direct_redis.git to /tmp/pip-req-build-o5rxb73a
  Running command git clone -q https://github.com/pbs/direct_redis.git /tmp/pip-req-build-o5rxb73a
[31m  ERROR: Error [Errno 2] No such file or directory: 'git' while executing command git clone -q https://github.com/pbs/direct_redis.git /tmp/pip-req-build-o5rxb73a[0m
[31mERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?[0m
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m21212121/m21212121_q10_t0.py /platform/output/s01/v4/m21212121/m21212121_q10_t0.csv /platform/expected/s01/q10.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m21212121/m21212121_q10_t0.py", line 19, in <module>
    orders_df = pd.read_msgpack(redis_client.get('orders'))
AttributeError: module 'pandas' has no attribute 'read_msgpack'
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m21212121/m21212121_q11_t0.py /platform/output/s01/v4/m21212121/m21212121_q11_t0.csv /platform/expected/s01/q11.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m21212121/m21212121_q11_t0.py", line 2, in <module>
    import redis_functions
ModuleNotFoundError: No module named 'redis_functions'
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m21212121/m21212121_q12_t0.py /platform/output/s01/v4/m21212121/m21212121_q12_t0.csv /platform/expected/s01/q12.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m21212121/m21212121_q12_t0.py", line 30, in <module>
    orders_df = pd.read_json(orders_str)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m21212121/m21212121_q13_t0.py /platform/output/s01/v4/m21212121/m21212121_q13_t0.csv /platform/expected/s01/q13.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m21212121/m21212121_q13_t0.py", line 41, in <module>
    main()
  File "/platform/source/s01/v4/m21212121/m21212121_q13_t0.py", line 19, in main
    orders = get_redis_data()
  File "/platform/source/s01/v4/m21212121/m21212121_q13_t0.py", line 14, in get_redis_data
    orders = pd.read_json(orders)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m21212121/m21212121_q14_t0.py /platform/output/s01/v4/m21212121/m21212121_q14_t0.csv /platform/expected/s01/q14.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m21212121/m21212121_q14_t0.py", line 16, in <module>
    part_df = pd.DataFrame(eval(redis_conn.get('part')))  # Dangerous: eval should be replaced with a safe parser in production
TypeError: eval() arg 1 must be a string, bytes or code object
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m21212121/m21212121_q15_t0.py /platform/output/s01/v4/m21212121/m21212121_q15_t0.csv /platform/expected/s01/q15.csv
Query results have been successfully written to query_output.csv.
Score.fail_missing_output
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m21212121/m21212121_q16_t0.py /platform/output/s01/v4/m21212121/m21212121_q16_t0.csv /platform/expected/s01/q16.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m21212121/m21212121_q16_t0.py", line 31, in <module>
    part_data_csv = redis_client.get('part').decode('utf-8')
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'decode'
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m21212121/m21212121_q17_t0.py /platform/output/s01/v4/m21212121/m21212121_q17_t0.csv /platform/expected/s01/q17.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m21212121/m21212121_q17_t0.py", line 15, in <module>
    if part_data:
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/generic.py", line 1466, in __nonzero__
    raise ValueError(
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m21212121/m21212121_q18_t0.py /platform/output/s01/v4/m21212121/m21212121_q18_t0.csv /platform/expected/s01/q18.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m21212121/m21212121_q18_t0.py", line 19, in <module>
    orders = pd.read_json(orders_df_str)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m21212121/m21212121_q19_t0.py /platform/output/s01/v4/m21212121/m21212121_q19_t0.csv /platform/expected/s01/q19.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m21212121/m21212121_q19_t0.py", line 39, in <module>
    part_df = execute_redis_query()
  File "/platform/source/s01/v4/m21212121/m21212121_q19_t0.py", line 14, in execute_redis_query
    part_df = pd.read_json(redis_client.get('part'))
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m21212121/m21212121_q1_t0.py /platform/output/s01/v4/m21212121/m21212121_q1_t0.csv /platform/expected/s01/q1.csv
The query results have been written to query_output.csv
>>> Expected ((4, 10))
   AVG_DISC     AVG_PRICE    AVG_QTY  COUNT_ORDER L_LINESTATUS L_RETURNFLAG  SUM_BASE_PRICE    SUM_CHARGE  SUM_DISC_PRICE  SUM_QTY
0  0.050145  36002.123829  25.537587       147790            F            A    5.320754e+09  5.256751e+09    5.054096e+09  3774200
1  0.049394  35521.326916  25.300664         3765            F            N    1.337378e+08  1.322863e+08    1.271324e+08    95257
2  0.050096  36000.924688  25.545538       292000            O            N    1.051227e+10  1.038558e+10    9.986238e+09  7459297
3  0.049989  35994.029214  25.525944       148301            F            R    5.337951e+09  5.274406e+09    5.071819e+09  3785523

>>> Actual ((4, 10))
   AVG_DISC     AVG_PRICE    AVG_QTY  COUNT_ORDER L_LINESTATUS L_RETURNFLAG  SUM_BASE_PRICE    SUM_CHARGE  SUM_DISC_PRICE  SUM_QTY
0  0.050145  36002.123829  25.537587       147790            F            A    5.320754e+09  5.256751e+09    5.054096e+09  3774200
1  0.049394  35521.326916  25.300664         3765            F            N    1.337378e+08  1.322863e+08    1.271324e+08    95257
2  0.050096  36000.924688  25.545538       292000            O            N    1.051227e+10  1.038558e+10    9.986238e+09  7459297
3  0.049989  35994.029214  25.525944       148301            F            R    5.337951e+09  5.274406e+09    5.071819e+09  3785523

Head row similarity: 1.0
Score.success_approx
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m21212121/m21212121_q20_t0.py /platform/output/s01/v4/m21212121/m21212121_q20_t0.csv /platform/expected/s01/q20.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m21212121/m21212121_q20_t0.py", line 17, in <module>
    pandas_part = pd.DataFrame(eval(redis.get('part')))
TypeError: eval() arg 1 must be a string, bytes or code object
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m21212121/m21212121_q21_t0.py /platform/output/s01/v4/m21212121/m21212121_q21_t0.csv /platform/expected/s01/q21.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m21212121/m21212121_q21_t0.py", line 71, in <module>
    main()
  File "/platform/source/s01/v4/m21212121/m21212121_q21_t0.py", line 61, in main
    nation_df, orders_df = fetch_redis_data(redis_client)
  File "/platform/source/s01/v4/m21212121/m21212121_q21_t0.py", line 20, in fetch_redis_data
    nation_df = pd.read_msgpack(redis_client.get('nation'))
AttributeError: module 'pandas' has no attribute 'read_msgpack'
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m21212121/m21212121_q22_t0.py /platform/output/s01/v4/m21212121/m21212121_q22_t0.csv /platform/expected/s01/q22.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m21212121/m21212121_q22_t0.py", line 44, in <module>
    orders_df = pd.read_msgpack(redis_client.get('orders'))
AttributeError: module 'pandas' has no attribute 'read_msgpack'
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m21212121/m21212121_q2_t0.py /platform/output/s01/v4/m21212121/m21212121_q2_t0.csv /platform/expected/s01/q2.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m21212121/m21212121_q2_t0.py", line 25, in <module>
    nation_df = redis_to_df('nation')
  File "/platform/source/s01/v4/m21212121/m21212121_q2_t0.py", line 19, in redis_to_df
    table_data = json.loads(table_data)
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not DataFrame
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m21212121/m21212121_q3_t0.py /platform/output/s01/v4/m21212121/m21212121_q3_t0.csv /platform/expected/s01/q3.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m21212121/m21212121_q3_t0.py", line 36, in <module>
    orders_df = pd.read_json(orders, orient='index')
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m21212121/m21212121_q4_t0.py /platform/output/s01/v4/m21212121/m21212121_q4_t0.csv /platform/expected/s01/q4.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m21212121/m21212121_q4_t0.py", line 29, in <module>
    orders_df = pd.read_json(orders_str)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m21212121/m21212121_q5_t0.py /platform/output/s01/v4/m21212121/m21212121_q5_t0.csv /platform/expected/s01/q5.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m21212121/m21212121_q5_t0.py", line 29, in <module>
    nation_df = pd.read_json(r.get('nation'))
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 760, in read_json
    json_reader = JsonReader(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 861, in __init__
    data = self._get_data_from_filepath(filepath_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/json/_json.py", line 901, in _get_data_from_filepath
    self.handles = get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 707, in get_handle
    if _is_binary_mode(path_or_buf, mode) and "b" not in mode:
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 1167, in _is_binary_mode
    return isinstance(handle, _get_binary_io_classes()) or "b" in getattr(
TypeError: argument of type 'method' is not iterable
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m21212121/m21212121_q6_t0.py /platform/output/s01/v4/m21212121/m21212121_q6_t0.csv /platform/expected/s01/q6.csv
>>> Expected ((1, 1))
        REVENUE
0  7.115407e+06

>>> Actual ((1, 1))
        REVENUE
0  1.180342e+07

Head row similarity: 0.8064516129032258
Score.success_approx_manual
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m21212121/m21212121_q7_t0.py /platform/output/s01/v4/m21212121/m21212121_q7_t0.csv /platform/expected/s01/q7.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m21212121/m21212121_q7_t0.py", line 19, in <module>
    nation_df = pd.read_json(redis_client.get('nation').decode('utf-8'))
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'decode'
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m21212121/m21212121_q8_t0.py /platform/output/s01/v4/m21212121/m21212121_q8_t0.csv /platform/expected/s01/q8.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m21212121/m21212121_q8_t0.py", line 20, in <module>
    nation_df = pd.read_msgpack(redis_client.get('nation'))
AttributeError: module 'pandas' has no attribute 'read_msgpack'
Score.fail_execute
python /dbknitter/dbknitter/grader.py /platform/source/s01/v4/m21212121/m21212121_q9_t0.py /platform/output/s01/v4/m21212121/m21212121_q9_t0.csv /platform/expected/s01/q9.csv
Traceback (most recent call last):
  File "/platform/source/s01/v4/m21212121/m21212121_q9_t0.py", line 40, in <module>
    nation_df = nation_df.astype({'N_NATIONKEY': 'int32'})
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/generic.py", line 6290, in astype
    raise KeyError(
KeyError: "Only a column name can be used for the key in a dtype mappings argument. 'N_NATIONKEY' not found in columns."
Score.fail_execute
